### ISSUE TITLE
Slf4jReporter failing on JDK9+ (Upgrade Dropwizard Metrics to 4.0.0)

### ISSUE THREAD

**Issue by brunojcm** [ktorio/ktor#1003]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Netty

### JVM Version, Operating System and Relevant Context
Oracle Corporation OpenJDK 64-Bit Server VM 11.0.2+9 (11)

### Feedback
I get the following error when doing

```
    val logger = LoggerFactory.getLogger("WebApiApplication")
    install(Metrics) {
        Slf4jReporter.forRegistry(registry)
                .outputTo(logger)
                .convertRatesTo(TimeUnit.SECONDS)
                .convertDurationsTo(TimeUnit.MILLISECONDS)
                .build()
                .start(1, TimeUnit.MINUTES)
    }

```
:
```
11:26:51.026 [metrics-logger-reporter-1-thread-1] INFO  WebApiApplication - type=GAUGE, name=jvm.attributes.name, value=40823@brunojcm-macbook
11:26:51.026 [metrics-logger-reporter-1-thread-1] INFO  WebApiApplication - type=GAUGE, name=jvm.attributes.uptime, value=302204
11:26:51.026 [metrics-logger-reporter-1-thread-1] INFO  WebApiApplication - type=GAUGE, name=jvm.attributes.vendor, value=Oracle Corporation OpenJDK 64-Bit Server VM 11.0.2+9 (11)
11:26:51.026 [metrics-logger-reporter-1-thread-1] ERROR com.codahale.metrics.ScheduledReporter - Exception thrown from Slf4jReporter#report. Exception was suppressed.
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getOpenFileDescriptorCount() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @2e2ff723
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340) ~[?:?]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280) ~[?:?]
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198) ~[?:?]
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192) ~[?:?]
	at com.codahale.metrics.jvm.FileDescriptorRatioGauge.invoke(FileDescriptorRatioGauge.java:48) ~[metrics-jvm-3.2.4.jar:3.2.4]
	at com.codahale.metrics.jvm.FileDescriptorRatioGauge.getRatio(FileDescriptorRatioGauge.java:35) ~[metrics-jvm-3.2.4.jar:3.2.4]
	at com.codahale.metrics.RatioGauge.getValue(RatioGauge.java:64) ~[metrics-core-3.2.4.jar:3.2.4]
	at com.codahale.metrics.RatioGauge.getValue(RatioGauge.java:11) ~[metrics-core-3.2.4.jar:3.2.4]
	at com.codahale.metrics.Slf4jReporter.logGauge(Slf4jReporter.java:306) ~[metrics-core-3.2.4.jar:3.2.4]
	at com.codahale.metrics.Slf4jReporter.report(Slf4jReporter.java:220) ~[metrics-core-3.2.4.jar:3.2.4]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:235) ~[metrics-core-3.2.4.jar:3.2.4]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:174) [metrics-core-3.2.4.jar:3.2.4]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) [?:?]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
```

Based on my quick research, I believe upgrading to Dropwizard Metrics 4 would fix that issue (see https://metrics.dropwizard.io/4.0.0/about/release-notes.html), but as this version was released more 
than 1 year ago, I understand that there must be something preventing Ktor to use 4.x version.

I tried to naively replace the dependencies by the 4.x ones, like
```
        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
            <version>4.0.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-jvm</artifactId>
            <version>4.0.0</version>
            <scope>compile</scope>
        </dependency>
```
but that didn't went well (as one would kind of expect):
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/codahale/metrics/JvmAttributeGaugeSet
	at io.ktor.metrics.Metrics$Feature.install(Metrics.kt:37)
	at io.ktor.metrics.Metrics$Feature.install(Metrics.kt:22)
	at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:59)
	at com.visagio.internal.sgv.web.api.WebApiServerKt.mainModule(WebApiServer.kt:52)
	at com.visagio.internal.sgv.web.api.WebApiServerKt$main$server$1.invoke(WebApiServer.kt:40)
	at com.visagio.internal.sgv.web.api.WebApiServerKt$main$server$1.invoke(WebApiServer.kt)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:279)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:127)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:247)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:106)
	at com.visagio.internal.sgv.web.api.WebApiServerKt.main(WebApiServer.kt:45)
	at com.visagio.internal.sgv.web.api.WebApiServerKt.main(WebApiServer.kt)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.JvmAttributeGaugeSet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 more
```

This is probably part of #321, but I'm reporting a separated issue because that one has too many things going on already.

Would you be interested in a PR for that?
Please, let me know how I can help.

**Comment by brunojcm** [comment]
`JvmAttributeGaugeSet` seems now to be on a different package:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/251695/54080371-14036e00-4329-11e9-96a9-6fa6b729b84a.png">

**Comment by herveDarritchon** [comment]
I have the same issue using Ktor (ktorVersion = "1.1.4") and Metrics.
Ktor engin is also Netty
Java open JDK v10.0.2
```
2019-04-16 10:57:49.277 [metrics-logger-reporter-1-thread-1] ERROR c.codahale.metrics.ScheduledReporter - Exception thrown from Slf4jReporter#report. Exception was suppressed.
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getOpenFileDescriptorCount() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @18317edc
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.codahale.metrics.jvm.FileDescriptorRatioGauge.invoke(FileDescriptorRatioGauge.java:48)
	at com.codahale.metrics.jvm.FileDescriptorRatioGauge.getRatio(FileDescriptorRatioGauge.java:35)
	at com.codahale.metrics.RatioGauge.getValue(RatioGauge.java:64)
	at com.codahale.metrics.RatioGauge.getValue(RatioGauge.java:11)
	at com.codahale.metrics.Slf4jReporter.logGauge(Slf4jReporter.java:306)
	at com.codahale.metrics.Slf4jReporter.report(Slf4jReporter.java:220)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:235)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:174)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

This is my Ktor conf about logging :
```
 install(Metrics) {
        Slf4jReporter
            .forRegistry(registry)
            .outputTo(log)
            .convertRatesTo(TimeUnit.SECONDS)
            .convertDurationsTo(TimeUnit.MILLISECONDS)
            .withLoggingLevel(Slf4jReporter.LoggingLevel.DEBUG)
            .build()
            .start(10, TimeUnit.SECONDS)
    }
```

**Comment by bitkid** [comment]
same problem with ktor 1.2.4 and jvm
openjdk 11.0.2 2019-01-15 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.2+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7-LTS, mixed mode, sharing)

**Comment by brunojcm** [comment]
It seems fixed by https://github.com/ktorio/ktor/pull/1329, everything is working for me in Ktor 1.3.0, DropWizard is now 4.1.0 and so far no problems with JDK 11.
