### ISSUE TITLE
kotlinx.coroutines.DispatchException

### ISSUE THREAD

**Issue by hoangtranwork** [ktorio/ktor#1031]
### Ktor Version
1.1.3
### Ktor Engine Used(client or server and name)
io.ktor:ktor-server-netty
### JVM Version, Operating System and Relevant Context
Java 1.8 on Ubuntu
### Feedback
This happen after handling some POST request, after that the server is no longer serving
### Stacktrace
```
01:06:21.878 w | A task raised an exception. Task: DispatchedContinuation[io.netty.channel.nio.NioEventLoop@f78a47e, Continuation at io.ktor.server.netty.cio.RequestBodyHandler$job$1.invokeSuspend(RequestBodyHandler.kt:29)@1454f6dc]
kotlinx.coroutines.DispatchException: Unexpected exception running DispatchedContinuation[io.netty.channel.nio.NioEventLoop@f78a47e, Continuation at io.ktor.server.netty.cio.RequestBodyHandler$job$1.invokeSuspend(RequestBodyHandler.kt:29)@1454f6dc]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:237) ~[kotlinx-coroutines-core-1.1.1.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.24.Final.jar:4.1.24.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by e5l** [comment]
Hi @hoangtranwork, thanks for the report

Could you reproduce the problem with `1.3.2`?

It looks like a memory leak. Could you provide how you're handling the post request?
