### ISSUE TITLE
"No Client ALPNProcessors!" error at Ktor Http Client Jetty

### ISSUE THREAD

**Issue by davidasync** [ktorio/ktor#1136]
### Ktor Version
1.2
### Ktor Engine Used(client or server and name)
client jetty
### JVM Version, Operating System and Relevant Context
Java 8
### Feedback
Here's my code
```
package com.playground.kt.http.client.ktor

import io.ktor.client.HttpClient
import io.ktor.client.engine.jetty.Jetty
import io.ktor.client.request.*
import io.ktor.client.response.HttpResponse
import kotlinx.coroutines.*
import org.eclipse.jetty.util.ssl.SslContextFactory

suspend fun main () = coroutineScope {
    var counter = 1
    val client = HttpClient(Jetty) {
        engine {
            threadsCount = 4
            pipelining = true
            sslContextFactory = SslContextFactory()
        }
    }

    val response = client.get<HttpResponse>("https://httpbin.org/get")

    println(response.status)
}
```

It would produce error like this
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalStateException: No Client ALPNProcessors!
	at org.eclipse.jetty.alpn.client.ALPNClientConnectionFactory.<init>(ALPNClientConnectionFactory.java:55)
	at org.eclipse.jetty.http2.client.HTTP2Client.lambda$doStart$1(HTTP2Client.java:160)
	at org.eclipse.jetty.http2.client.HTTP2Client$ClientSelectorManager.newConnection(HTTP2Client.java:476)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:263)
	at org.eclipse.jetty.io.ManagedSelector.access$1900(ManagedSelector.java:61)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:924)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: org.eclipse.jetty.alpn.ALPN must be on JVM boot classpath
		at org.eclipse.jetty.alpn.java.client.OpenJDK8ClientALPNProcessor.init(OpenJDK8ClientALPNProcessor.java:43)
		at org.eclipse.jetty.alpn.client.ALPNClientConnectionFactory.<init>(ALPNClientConnectionFactory.java:75)
		... 8 more
	Suppressed: java.lang.UnsupportedClassVersionError: org/eclipse/jetty/alpn/java/client/JDK9ClientALPNProcessor has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
		at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
		at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
		at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
		at org.eclipse.jetty.alpn.client.ALPNClientConnectionFactory.<init>(ALPNClientConnectionFactory.java:63)
		... 8 more
```

**Comment by cy6erGn0m** [comment]
> 	Suppressed: java.lang.UnsupportedClassVersionError: org/eclipse/jetty/alpn/java/client/JDK9ClientALPNProcessor has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by e5l** [comment]
Hi @davidasync, thanks for the report.
Please make sure that you added the proper jetty-alpn dependency for your jdk version:

https://ktor.io/advanced/http2.html#alpn-implementation
https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-troubleshooting

**Comment by davidasync** [comment]
> Hi @davidasync, thanks for the report.
> Please make sure that you added the proper jetty-alpn dependency for your jdk version:
> 
> https://ktor.io/advanced/http2.html#alpn-implementation
> https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-troubleshooting

Ahh I miss that documentation, thank you ~
