### ISSUE TITLE
GET request as a ByteReadChannel causes crash in Ktor 1.2.0 on Android

### ISSUE THREAD

**Issue by Thomas-Vos** [ktorio/ktor#1140]
### Ktor Version
1.2.0 (Version `1.2.0-alpha-1.3.0-eap-125` works fine, error started after version `1.2.0-rc`)

### Ktor Engine Used(client or server and name)
OkHttp on Android

### JVM Version, Operating System and Relevant Context
Android 9 (did not test on other versions)

### Feedback
After updating to Ktor `1.2.0` I keep getting the following error:
```
2019-05-16 17:58:08.402 30329-30329/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 30329
    java.lang.IllegalStateException: Operation is already in progress
        at kotlinx.coroutines.io.ByteBufferChannel.suspensionForSize(ByteBufferChannel.kt:2984)
        at kotlinx.coroutines.io.ByteBufferChannel.access$suspensionForSize(ByteBufferChannel.kt:21)
        at kotlinx.coroutines.io.ByteBufferChannel.readSuspendImpl(ByteBufferChannel.kt:2309)
        at kotlinx.coroutines.io.ByteBufferChannel.readSuspend(ByteBufferChannel.kt:2249)
        at kotlinx.coroutines.io.ByteBufferChannel.readAvailableSuspend(ByteBufferChannel.kt:587)
        at kotlinx.coroutines.io.ByteBufferChannel.readAvailable(ByteBufferChannel.kt:555)
        at kotlinx.coroutines.io.jvm.javaio.InputAdapter$loop$1.loop(Blocking.kt:31)
        at kotlinx.coroutines.io.jvm.javaio.InputAdapter$loop$1$loop$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.io.jvm.javaio.UnsafeBlockingTrampoline.dispatch(Blocking.kt:276)
        at kotlinx.coroutines.DispatchedContinuation.resumeWith(Dispatched.kt:104)
        at kotlinx.coroutines.io.jvm.javaio.BlockingAdapter.submitAndAwait(Blocking.kt:213)
        at kotlinx.coroutines.io.jvm.javaio.BlockingAdapter.submitAndAwait(Blocking.kt:186)
        at kotlinx.coroutines.io.jvm.javaio.InputAdapter.read(Blocking.kt:55)
        at okio.Okio$2.read(Okio.java:140)
        at okio.RealBufferedSource.request(RealBufferedSource.java:72)
        at com.squareup.moshi.JsonUtf8Reader.nextNonWhitespace(JsonUtf8Reader.java:996)
        at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:319)
        at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:193)
        at (removed some lines of my code)
        at com.myapp.MyClass$initialize$2.invokeSuspend(MyClass.kt:99)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2019-05-16 17:58:08.402 30329-30329/com.myapp E/AndroidRuntime:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
This is the code which causes the problem:
```kotlin
GlobalScope.launch {
    val client = HttpClient(OkHttp)
    val channel = client.get<ByteReadChannel> {
        url("https://kotlinlang.org/")
    }
    channel.readRemaining()
}
```
[Here is an Android sample project](https://github.com/ktorio/ktor/files/3203364/KtorIllegalStateException.zip) which reproduces the issue. Run the app and it will throw the exception.

(related discussion on Slack: https://kotlinlang.slack.com/archives/C0A974TJ9/p1558022742209800)

**Comment by e5l** [comment]
Hi @Thomas-Vos, thanks for the report. It's a bug and will be fixed in next release.

Consider using `client.get<HttpResponse>` for now.

**Comment by feresr** [comment]
Hi! I'm still experiencing this issue on 1.2.2

```
java.lang.IllegalStateException: 
  at kotlinx.coroutines.io.ByteBufferChannel.suspensionForSize (ByteBufferChannel.java)
  at kotlinx.coroutines.io.ByteBufferChannel.access$suspensionForSize (ByteBufferChannel.java)
  at kotlinx.coroutines.io.ByteBufferChannel.readSuspendImpl (ByteBufferChannel.java)
  at kotlinx.coroutines.io.ByteBufferChannel.readSuspend (ByteBufferChannel.java)
  at kotlinx.coroutines.io.ByteBufferChannel.discardSuspend (ByteBufferChannel.java)
  at kotlinx.coroutines.io.ByteBufferChannel.discard (ByteBufferChannel.java)
  at kotlinx.coroutines.io.ByteReadChannelKt.discard (ByteReadChannelKt.java)
  at io.ktor.client.response.HttpResponse$close$1.invokeSuspend (HttpResponse.java)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.b (BaseContinuationImpl.java:6)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:784)
```


I'm fairly certain this happens here in my code but cant say for sure

```
    private fun download(url: String) = flow {
        try {
            val response = client.endpoint(url)
            val data = ByteArray(response.contentLength()!!.toInt())
            var offset = 0
            do {
                val currentRead = response.content.readAvailable(data, offset, data.size)
                offset += currentRead
                emit(Download.Progress(round(offset.toFloat() * 100f / data.size.toFloat()).toInt()))
            } while (currentRead > 0)
            response.close()
            emit(Download.Success(data))
        } catch (e: Exception) {
            crashlytics.logException(e)
            emit(Download.Error)
        }
    }

```

**Comment by Thomas-Vos** [comment]
It should be fixed in 1.2.3-rc and soon 1.2.3 as well

**Comment by feresr** [comment]
I haven't reproduced the issue myself, I dumped everything Firebase Crashlytics reports into this gist:
https://gist.github.com/feresr/c38e80fb36f050e9fa4951498d4d3684

**Comment by feresr** [comment]
uhm, I just noticed that the report from Crashlytics looks different from the one on the Google console. I'm not sure if they are the same issue. I'll update to 1.2.3-rc and report back.
