### ISSUE TITLE
Support for Lists of Query Parameters in Locations

### ISSUE THREAD

**Issue by jebbench** [ktorio/ktor#1143]
### Ktor Version
1.2.0

### Ktor Engine Used(client or server and name)
Netty Server

### JVM Version, Operating System and Relevant Context
Java 11 - Ubuntu

### Feedback
My use case is passing a number of sort options in the query string as parameters - something along the lines of: `?sort=key1:DESC&sort=key2:ASC&sort=key3:ASC`.

I have created a Location class:
```
@io.ktor.locations.Location("")
data class Search (val sort: List<SortParam> = emptyList())
```
and a converter:
```
convert<List<SortParam>> {
    decode { values, _ ->
        values.map {
            ...
            SortParam(...)
        }
    }
    encode {
        // TODO
        emptyList()
    }
}
```
Running this give the following stack trace:
```
io.ktor.features.ParameterConversionException: Request parameter sort couldn't be parsed/converted to java.util.List<dev.r36.barker.model.url.SortParam>
	at io.ktor.locations.Locations.createFromParameters(Locations.kt:75)
	at io.ktor.locations.Locations.create(Locations.kt:54)
	at io.ktor.locations.Locations.resolve(Locations.kt:170)
	at io.ktor.locations.Locations.resolve(Locations.kt:162)
	at io.ktor.locations.LocationKt$handle$1.invokeSuspend(Location.kt:210)
	at io.ktor.locations.LocationKt$handle$1.invoke(Location.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:106)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
	at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:118)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:36)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:26)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:20)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.ktor.util.DataConversionException: Type class dev.r36.barker.model.url.SortParam is not supported in default data conversion service
	at io.ktor.util.DefaultConversionService.convert(ConversionService.kt:83)
	at io.ktor.util.DefaultConversionService.fromValues(ConversionService.kt:57)
	at io.ktor.features.DataConversion.fromValues(DataConversion.kt:19)
	at io.ktor.locations.Locations.createFromParameters(Locations.kt:73)
	... 54 common frames omitted
```

How should I approach this problem?

As a workaround I've had to create a `SortParamCollection` class which works but isn't ideal as I lose a lot of the utility methods such as `listOf(...)`:
```
class SortParamCollection : ArrayList<SortParam>()
```

```
@io.ktor.locations.Location("")
data class Search (val sort: SortParamCollection = SortParamCollection())
```

**Comment by chrisjenx** [comment]
Did this get fixed?

**Comment by chrisjenx** [comment]
Guess not:
```
o.ktor.features.ParameterConversionException: Request parameter eventIds couldn't be parsed/converted to java.util.Collection<java.util.UUID>
```

**Comment by chrisjenx** [comment]
Also if looking into this, with `Location`s you cant do `url?param[]=value1&param[]=value2` with this as you'd need to name your parameters in the location class the same way.
(Guessing we'd need some annotation or something?)

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-616">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
