### ISSUE TITLE
"Invalid TLS record type" crash

### ISSUE THREAD

**Issue by hazae41** [ktorio/ktor#1200]
### Ktor Version
1.2.1

### Ktor Engine Used(client or server and name)
https://github.com/hazae41/multisockets/blob/master/ktor.gradle

### JVM Version, Operating System and Relevant Context
It's from a Minecraft server hosting (linux maybe?)

### Feedback
    [17:12:49 WARN]: Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalArgumentException: Invalid TLS record type code: 170
    [17:12:49 WARN]: at io.ktor.network.tls.TLSRecordType$Companion.byCode(TLSRecordType.kt:27)
    [17:12:49 WARN]: at io.ktor.network.tls.ParserKt.readTLSRecord(Parser.kt:18)
    [17:12:49 WARN]: at io.ktor.network.tls.ParserKt$readTLSRecord$1.invokeSuspend(Parser.kt)
    [17:12:49 WARN]: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    [17:12:49 WARN]: at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
    [17:12:49 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    [17:12:49 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    [17:12:49 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by e5l** [comment]
Hi @hazae41, do you have self-contained reproducer?

**Comment by hazae41** [comment]
No, sorry

**Comment by cy6erGn0m** [comment]
An interesting fact: 170 = 0xaa, most likely it is not TLS stream at all.

**Comment by e5l** [comment]
As @cy6erGn0m mentioned, it looks like the connection is not using TLS, so the error message is correct. If you have any cases to reproduce, please reopen the issue.
