### ISSUE TITLE
UnsatisfiedLinkError with Netty

### ISSUE THREAD

**Issue by guenhter** [ktorio/ktor#1203]
### Ktor Version
1.2.2

### Ktor Engine Used(client or server and name)
```
val ktorVersion = "1.2.2"
implementation("io.ktor:ktor-server-core:$ktorVersion")
implementation("io.ktor:ktor-server-netty:$ktorVersion")
implementation("io.ktor:ktor-auth:$ktorVersion")
implementation("io.ktor:ktor-websockets:$ktorVersion")
```

### JVM Version, Operating System and Relevant Context
/usr/lib/jvm/jdk-11.0.2/bin/java

### Feedback
Starting the Ktor application with Netty gives me the error below.
The program runs without problems. All rest requests are working but the error still is not nice. 
I guess it's a more Netty related Problem but I post it here to discuss if e.g. missing dependencies should be included to avoid this error at startup time.

```
13:30:41.590 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - netty_transport_native_epoll cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:201)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create(NettyApplicationEngine.kt:186)
	at io.ktor.server.netty.NettyApplicationEngine.<init>(NettyApplicationEngine.kt:74)
	at io.ktor.server.netty.Netty.create(Embedded.kt:14)
	at io.ktor.server.netty.Netty.create(Embedded.kt:12)
	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:79)
	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:67)
	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:36)
	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer$default(EmbeddedServer.kt:34)
	at com.frauscher.sensor.onyxsimulator.ApplicationKt.runOnyxSimulator(Application.kt:66)
	at com.frauscher.sensor.onyxsimulator.ApplicationKt.main(Application.kt:62)
	at com.frauscher.sensor.onyxsimulator.ApplicationKt.main(Application.kt)
	Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
		at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
		at java.base/java.lang.System.loadLibrary(System.java:1867)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
		... 15 common frames omitted
```

**Comment by cy6erGn0m** [comment]
Since 1.2.2 netty engine is trying to initialize native transport is available with fallback to NIO implementation. This is not an error. The problem is that you have wrong logger configuration so you see netty debug log.

**Comment by cy6erGn0m** [comment]
FYI: https://netty.io/wiki/native-transports.html

**Comment by guenhter** [comment]
Oh true. This is only logged on DEBUG level. Appreciate that. I'll turn off DEBUG here. Thx.
