### ISSUE TITLE
Server receiving null json value 

### ISSUE THREAD

**Issue by akram09** [ktorio/ktor#1231]
**Ktor Version and Engine Used**
  Ktor Version : 1.2.2 /  Engine Used Netty , modules included gson , ktor-auth

**Describe the bug**
 the server is receiving a null json where when testing with postman i'm sending this json : 
```
{
	"hello":"hdhhdehhde"
}
```
 when i do a `receiveText()` it print me the json that i want , but when i do `call.receive(SignUpParam::class)`  i get this exception throwned 
  ```
2019-07-12 18:07:11.198 [nioEventLoopGroup-4-1] ERROR Application - Unhandled: POST - /signUp
io.ktor.gson.UnsupportedNullValuesException: Receiving null values is not supported
	at io.ktor.gson.GsonConverter.convertForReceive(GsonSupport.kt:42)
	at io.ktor.features.ContentNegotiation$Feature$install$3.invokeSuspend(ContentNegotiation.kt:153)
	at io.ktor.features.ContentNegotiation$Feature$install$3.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.request.ApplicationReceiveFunctionsKt.receive(ApplicationReceiveFunctions.kt:73)
	at akram.kero.todoapp.presentation.ApplicationKt$module$4$1$2.invokeSuspend(Application.kt:104)
	at akram.kero.todoapp.presentation.ApplicationKt$module$4$1$2.invoke(Application.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletionInternal(Scopes.kt:32)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:311)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:237)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:851)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:813)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:789)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`
there is my code 
  ```
```
fun Application.module(){
     val controller:AuthController by inject()
    install(CallLogging){
        level = Level.DEBUG
     }
    install(ContentNegotiation){
       gson {
           setDateFormat(DateFormat.LONG)
            setPrettyPrinting()
        }
   }
    install(DefaultHeaders)
    install(Authentication){      
        basic("Basic-Auth"){
            realm = "todo.ktor.io.basic"
            validate {
                controller.validateBasicAuthUser(it)
            }
        }
    }
    routing {
       authenticate("Basic-Auth") {
           post("/signUp"){
                log.debug("entered the sign Up routes with ${call.receiveText()}")
                call.receive<Hello>()
                val user = call.receive(SignUpParam::class)
                controller.signUpUser(user).responde(call::respond)
            }
        }
    }
}

data class Hello(val hello:String)
```
**To Reproduce**
1. Just copy the snippet of code
2. Run using browser/curl/etc
3. See error

**Comment by cy6erGn0m** [comment]
One can receive request body content only once but you do it twice: `Hello` first.

**Comment by akram09** [comment]
After deleting `call.receiveText()` the exception is not thrown and the application works perfectly ,so the problem was that i can not call receive two times on an ApplicationCall?
