### ISSUE TITLE
Close frame causes kotlinx.coroutines.channels.ClosedSendChannelException in test

### ISSUE THREAD

**Issue by Leland-Takamine** [ktorio/ktor#1259]
ktor version: 1.2.2

The following test fails with the exception below. I would expect this to close gracefully and pass. Am I missing something here?

```kotlin
@Test
fun testClose() {
    withTestApplication {
        application.install(WebSockets)

        application.routing {
            webSocket("/") {
                incoming.consumeEach { }
            }
        }

        handleWebSocketConversation("/") { _, outgoing ->
            outgoing.send(Frame.Close())
        }
    }
}
```

Exception:
```
Channel was closed
kotlinx.coroutines.channels.ClosedSendChannelException: Channel was closed
	(Coroutine boundary)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:195)
	at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:175)
	at kotlinx.coroutines.channels.ChannelCoroutine.send$suspendImpl(ChannelCoroutine.kt)
	at kotlinx.coroutines.channels.ChannelCoroutine.send(ChannelCoroutine.kt)
	at kotlinx.coroutines.channels.LazyActorCoroutine.send(Actor.kt:156)
	at io.ktor.http.cio.websocket.WebSocketWriter.flush(WebSocketWriter.kt:136)
	at io.ktor.server.testing.TestApplicationEngine$handleWebSocketConversation$4.invokeSuspend(TestApplicationEngine.kt:234)
Caused by: kotlinx.coroutines.channels.ClosedSendChannelException: Channel was closed
	at kotlinx.coroutines.channels.Closed.getSendException(AbstractChannel.kt:1093)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:195)
	at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:175)
	at kotlinx.coroutines.channels.ChannelCoroutine.send$suspendImpl(ChannelCoroutine.kt)
	at kotlinx.coroutines.channels.ChannelCoroutine.send(ChannelCoroutine.kt)
	at kotlinx.coroutines.channels.LazyActorCoroutine.send(Actor.kt:156)
	at io.ktor.http.cio.websocket.WebSocketWriter.flush(WebSocketWriter.kt:136)
	at io.ktor.server.testing.TestApplicationEngine$handleWebSocketConversation$4.invokeSuspend(TestApplicationEngine.kt:234)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by e5l** [comment]
Hi @Leland-Takamine, thanks for the report.

@cy6erGn0m, it could be related to the fix in `1.1.2`.

**Comment by rivendell1984** [comment]
same issue in ktor version 1.2.3, I think the reason is `outgoingToBeProcessed` in `DefaultWebSocketSessionImpl` is closed before `send(Frame.Close())`

**Comment by zworkb** [comment]
I have tried it with 1.2.4, it still occurs, but not deterministically :(

**Comment by sebastianfast** [comment]
It still occurs in 1.2.6

**Comment by Stexxe** [comment]
Can't reproduce with Ktor 1.5.3.
