### ISSUE TITLE
Stacktraces are not recovered when thrown directly in interceptor

### ISSUE THREAD

**Issue by qwwdfsad** [ktorio/ktor#1267]
Kotlin version: current master
Reproducer: file `PipelineTest` in `io.ktor.tests.utils`

The following test:
```
@Test
fun testFailure() {
    val pipeline = pipeline()
    pipeline.intercept { subject -> bar() }
    pipeline.executeBlocking("some")
}

suspend fun bar() {
    withContext(Dispatchers.IO) { // Important: coroutine boundary
        barInternal(1)
    }
    yield()
}

suspend fun barInternal(i: Int) {
    yield() // Important: suspension point
    if (i == 1) throw RuntimeException()
    yield()
}
```

produces a proper stacktrace:
```
java.lang.RuntimeException
	at io.ktor.tests.utils.PipelineTest.barInternal(PipelineTest.kt:64)
	at io.ktor.tests.utils.PipelineTest$barInternal$1.invokeSuspend(PipelineTest.kt)
	(Coroutine boundary)
	at io.ktor.tests.utils.PipelineTest.bar(PipelineTest.kt:52)
	at io.ktor.tests.utils.PipelineTest$testFailure$2.invokeSuspend(PipelineTest.kt:46)
	at io.ktor.tests.utils.PipelineTest$executeBlocking$1.invokeSuspend(PipelineTest.kt:15)
```

Now replace 
```
withContext(Dispatchers.IO) { // Important: coroutine boundary
    barInternal(1)
}
```

with
```
barInternal(1)
```

and observe the following stacktrace:
```
java.lang.RuntimeException
	at io.ktor.tests.utils.PipelineTest.barInternal(PipelineTest.kt:63)
	at io.ktor.tests.utils.PipelineTest$barInternal$1.invokeSuspend(PipelineTest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
```

`bar` is no longer present in the stacktrace.

Why does it happen:
`SuspendFunctionGun` properly implements `CoroutineStackFrame` (thus the first example works), but handles exceptions by directly resuming root continuation, completely ignoring stacktrace recovery.

**Comment by qwwdfsad** [comment]
Some parts of the API may be missing in `kotlinx.coroutines` for such integration, so feel free to ping me

**Comment by Thomas-Vos** [comment]
Could this be related to my issue https://github.com/ktorio/ktor/issues/1263? The stacktrace does not show my code so I have trouble fixing that crash.

**Comment by e5l** [comment]
Merged in `master`.
