### ISSUE TITLE
Locations: Type class XYZ is not supported in default data conversion service

### ISSUE THREAD

**Issue by saschpe** [ktorio/ktor#1296]
**Ktor Version and Engine Used (client or server and name)**
```gradle
implementation("io.ktor:ktor-locations:1.2.3")
implementation("io.ktor:ktor-serialization:1.2.3")
```

**Describe the bug**
Default data conversions fails when nesting **Object -> Class -> Object -> Class** with the `@Location` annotation like in the following example (*Branch* is an object, *List* a class):
```kotlin

val branchList = Organization.ById.Branch.List(Organization.ById("abc"))
// Would become "/organizations/abc/branches"
val branchListHref = application.locations.href(organizationBranchList)
```

It yields the following error:
```
Type class Organization$ById is not supported in default data conversion service
io.ktor.util.DataConversionException: Type class Organization$ById is not supported in default data conversion service
	at io.ktor.util.DefaultConversionService.toValues(ConversionService.kt:46)
	at io.ktor.locations.Locations.pathAndQuery(Locations.kt:210)
	at io.ktor.locations.Locations.href(Locations.kt:222)
	at ...ApplicationTest$branch offices for organization$1.invoke(ApplicationTest.kt:183)
```

A similar version using nested **Object -> Class -> Class** works like expected (*BranchList* is a class):
```kotlin
val branchList = Organization.ById.BranchList(Organization.ById("abc"))
val branchListHref = application.locations.href(organizationBranchList)
```

Both are based on the following declaration of API routes:
```kotlin
@Location("/organizations")
object Organization {
    @Location("/")
    class List(val offset: Int = 0, val limit: Int = 20)
    @Location("/{id}")
    class ById(val id: String) {
        // 1)  Does not work
        @Location("/branches")
        object Branch {
            @Location("/")
            class List(val organization: Organization.ById, val offset: Int = 0, val limit: Int = 20)
            @Location("/{id}")
            class ById(val organization: Organization.ById, val id: String)
        }

        // 2) Works 
        @Location("/branches/")
        class BranchList(val organization: ById, val offset: Int = 0, val limit: Int = 20)
        @Location("/branches/{id}")
        class BranchById(val organization: ById, val id: String)
    }
}
```
Style *2)* seems more idiomatic as it allows to *POST* or *PUT* to Organization.ById.Branches (`/organizations/123/branches`) to create a new *Branch*.

**To Reproduce**
See above code example.

**Expected behavior**
Arbitrary nesting of locations should work.

**Comment by cy6erGn0m** [comment]
Unfortunately, currently, only direct parent types are supported. In case 1 `Organization.ById` is the parent of the parent.

**Comment by cy6erGn0m** [comment]
Please read #1660

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-569">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
