### ISSUE TITLE
Js ktor client - fails when calling suspend function inside a request builder block

### ISSUE THREAD

**Issue by anti-social** [ktorio/ktor#1321]
Ktor client version is: `1.2.4`

Don't know whether it is `ktor` or `kotlin-js` problem (I tend it is a tricky`kotlin-js` error, but could not reduce example to prove that). I'm trying to write multiplatform tests for ktor client:

```
import io.ktor.client.HttpClient
import io.ktor.client.engine.mock.MockEngine
import io.ktor.client.engine.mock.respond
import io.ktor.client.request.put
import io.ktor.http.ContentType
import io.ktor.http.content.TextContent
import kotlinx.coroutines.delay
import kotlin.test.Test
import kotlin.test.assertEquals

suspend fun getData(): Pair<String, String> {
    delay(10)
    return "Hello" to "world"
}

class NodeHttpTests {
    @Test
    fun testHttpClient() = runTest {
        val client = HttpClient(MockEngine) {
            engine {
                addHandler { request ->
                    assertEquals("example.com", request.url.host)
                    assertEquals("(Hello, world)", (request.body as TextContent).text)
                    respond("")
                }
            }
        }

        client.put("http://example.com") {
            // Move the following line out of the closure block to work
            val data = getData()

            body = TextContent(data.toString(), ContentType.Text.Plain)
        }
    }
}
```

On jvm platform test works fine. But on js it fails with an error:

```
{ CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[NodeDispatcher@2, [object Object]]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
    at DispatchedContinuation.DispatchedTask.handleFatalException_mseuzz$ (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:2833:16)
    at DispatchedContinuation.DispatchedTask.run (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:2826:10)
    at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:36148:15)
    at /home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:35964:30
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  'message_q7r8iu$_0':
   'Fatal exception in coroutines machinery for DispatchedContinuation[NodeDispatcher@2, [object Object]]. Please read KDoc to \'handleFatalException\' method and report this incident to maintainers',
  'cause_us9j0c$_0':
   { IllegalStateException: Job DeferredCoroutine{Cancelled}@1 is already complete or completing, but is being completed with CompletedExceptionally[JobCancellationException: DeferredCoroutine is cancelling; caused by TypeError: Cannot read property 'toString' of undefined; job=DeferredCoroutine{Cancelled}@1]; caused by JobCancellationException: DeferredCoroutine is cancelling; caused by TypeError: Cannot read property 'toString' of undefined; job=DeferredCoroutine{Cancelled}@1
       at IllegalStateException_init_0 (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlin/1.3.50/kotlin/exceptions.kt:66:44)
       at IllegalStateException_0 (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:35930:12)
       at DeferredCoroutine.JobSupport.makeCompletingOnce_42w2xh$ (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:4474:21)
       at DeferredCoroutine.AbstractCoroutine.resumeWith_tl1gpc$ (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:402:8)
       at Coroutine$getData.CoroutineImpl.resumeWith_tl1gpc$ (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlin/1.3.50/coroutines/Continuation.kt:53:5)
       at DispatchedContinuation.DispatchedTask.run (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:2803:22)
       at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:36148:15)
       at /home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:35964:30
       at process._tickCallback (internal/process/next_tick.js:61:11)
       at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
     'message_8yp7un$_0':
      'Job DeferredCoroutine{Cancelled}@1 is already complete or completing, but is being completed with CompletedExceptionally[JobCancellationException: DeferredCoroutine is cancelling; caused by TypeError: Cannot read property \'toString\' of undefined; job=DeferredCoroutine{Cancelled}@1]; caused by JobCancellationException: DeferredCoroutine is cancelling; caused by TypeError: Cannot read property \'toString\' of undefined; job=DeferredCoroutine{Cancelled}@1',
     'cause_th0jdv$_0': null,
     name: 'IllegalStateException' },
  name: 'CoroutinesInternalError' }
(node:32637) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at /home/alexk/projects/prom-kt/push/src/commonTest/kotlin/dev/evo/prometheus/push/NodeHttpTests.kt:36:37
    at Coroutine$NodeHttpTests$testHttpClient$lambda.doResume (/home/alexk/projects/prom-kt/build/js/packages/prometheus-kt-prometheus-kt-push-test/kotlin/prometheus-kt-prometheus-kt-push-test.js:253:63)
    at Coroutine$runTest$lambda.NodeHttpTests$testHttpClient$lambda [as local$closure$block] (/home/alexk/projects/prom-kt/push/src/commonTest/kotlin/dev/evo/prometheus/push/NodeHttpTests.kt:21:36)
    at Coroutine$runTest$lambda.doResume (/home/alexk/projects/prom-kt/test-util/src/jsMain/kotlin/dev/evo/prometheus/utilJs.kt:9:9)
    at Coroutine$runTest$lambda.CoroutineImpl.resumeWith_tl1gpc$ (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlin/1.3.50/kotlin/coroutines/CoroutineImpl.kt:47:35)
    at DispatchedContinuation.DispatchedTask.run (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:2806:22)
    at SetTimeoutBasedDispatcher$ScheduledMessageQueue.MessageQueue.process (/home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:36148:15)
    at /home/alexk/projects/prom-kt/build/js/packages_imported/kotlinx-coroutines-core/1.3.0/kotlinx-coroutines-core.js:35964:30
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
(node:32637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also the same error is here when using `Js` engine.

**Comment by anti-social** [comment]
It turned out there is a reported bug for kotlin js compiler: https://youtrack.jetbrains.com/issue/KT-32708

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-559">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
