### ISSUE TITLE
Apache client IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by j-mew-s** [ktorio/ktor#1449]
**Ktor Version and Engine Used (client or server and name)**
ktor version 1.2.4

**Describe the bug**
Under light usage, the ktor client got into a state where requests were no longer made and the following exception was seen with each subsequent attempt:
```
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
  at org.apache.http.util.Asserts.check(Asserts.java:46)
  at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
  at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
  at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:68)
  at io.ktor.client.engine.apache.ApacheHttpRequestKt.sendRequest(ApacheHttpRequest.kt:50)
  at io.ktor.client.engine.apache.ApacheEngine.execute(ApacheEngine.kt:23)
  at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(HttpClientEngine.kt:49)
  at io.ktor.client.engine.HttpClientEngine$install$1.invoke(HttpClientEngine.kt)
  at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
```

Clients are created with:
`HttpClient(Apache) {
  install(JsonFeature) {
    serializer = JacksonSerializer()
  }
}`

and consumed with:
`runBlocking {
  httpClient.use { it.submitForm<ResponseDataClass>(
    "<url>",
    parameters)
  }
}`

**To Reproduce**
I have only seen this behaviour once, but its impact is severe enough that I am reluctant to use the Apache client in production environments.

**Expected behavior**
The Apache client should not be cancelled or closed while ktor is running. It should be possible to make new connections.

**Comment by j-mew-s** [comment]
Me being stupid - I had passed an HttpClient instance rather than the provider and was trying to reuse a single instance.
Closing - sorry!

**Comment by lukaville** [comment]
@j-mew-s but in the [docs](https://hc.apache.org/httpclient-legacy/performance.html) for Apache Http client it is stated that it is better to reuse the client as in this case it will use warmed-up connection pool and thread pool. Have you faced any performance issues when using a new instance of http client per request?

**Comment by j-mew-s** [comment]
Hi @lukaville, no we haven't hit any issues so far, but thank you for highlighting the best practice on this front. I will aim to update our usage -
