### ISSUE TITLE
Executing a HttpStatement in a suspending main results in NPE

### ISSUE THREAD

**Issue by BartArys** [ktorio/ktor#1542]
**Ktor Version and Engine Used (client or server and name)**
io.ktor:ktor-client-cio:1.3.0-rc2 (JVM)

**Describe the bug**

Executing a `HttpStatement` in a `suspend` main function results in a `KotlinNullPointerException` being thrown. 

**To Reproduce**
1. Write the following
```kotlin
suspend fun main()  {
    val client = HttpClient(CIO)
    val statement = client.get<HttpStatement>("https://kotlinlang.org/")
    statement.execute()
}
```
2. Run the program 
3. See error

```
Exception in thread "main" kotlin.KotlinNullPointerException
	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.createCallContext(HttpClientEngine.kt:137)
	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.executeWithinCallContext(HttpClientEngine.kt:73)
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(HttpClientEngine.kt:56)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(HttpClientEngine.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.client.features.HttpSend$DefaultSender.execute(HttpSend.kt:98)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:62)
	at io.ktor.client.features.HttpSend$Feature$install$1.invoke(HttpSend.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(PipelineContext.kt:151)
	at io.ktor.client.features.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:87)
	at io.ktor.client.features.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.client.HttpClient.execute(HttpClient.kt:155)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:99)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:38)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:53)
	at ApplicationKt.main(Application.kt:10)
	at ApplicationKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at ApplicationKt.main(Application.kt)

Process finished with exit code 1
```

**Expected behavior**
The request executes without any exceptions.

**Comment by cy6erGn0m** [comment]
Fixed in 1.3.0
