### ISSUE TITLE
ktor-client 1.3.0 apache engine timeout exception handling

### ISSUE THREAD

**Issue by mcnaggets** [ktorio/ktor#1563]
After the client upgrade (Apache engine) to 1.3.0 timeout exceptions stopped to handle properly
```kotlin
fun main() {
    val env = applicationEngineEnvironment {
        module {
            main()
        }
        connector {
            host = "127.0.0.1"
            port = 80
        }
    }
    embeddedServer(Netty, env).start()


    val client = HttpClient(Apache) {
        engine {
            socketTimeout = 5
        }
    }
    runBlocking {
        print(client.get<String>("/"))
    }
}

fun Application.main() {
    install(CallLogging) {
        level = Level.INFO
    }
    routing {
        get("/") {
            delay(Duration.ofSeconds(10))
            call.respond("Hi")
        }
    }
}
```

It simply logs in the console 
`Exception in thread "main" kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelled}@4acf72b6` 
with no extra details

Expected:
- error cause
- program termination?

**Comment by dmitrievanthony** [comment]
Hi @mcnaggets, thanks for reporting!

I reproduces the problem with `1.3.0`. At the same time, I checked this code against the current master and got the following exception:

```
Exception in thread "main" java.util.concurrent.CancellationException: Failed to execute request
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at io.ktor.client.engine.apache.ApacheHttpRequestKt$sendRequest$$inlined$suspendCancellableCoroutine$lambda$2.failed(ApacheHttpRequest.kt:48)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:138)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:381)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.ktor.network.sockets.SocketTimeoutException: Socket timeout has been expired [url=http://localhost:8085/, socket_timeout=unknown] ms
	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:170)
	at io.ktor.client.engine.apache.ApacheHttpRequestKt$sendRequest$$inlined$suspendCancellableCoroutine$lambda$2.failed(ApacheHttpRequest.kt:44)
	... 14 more
Caused by: java.net.SocketTimeoutException: 5 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
```

I guess it's more meaningful. It will be released in `1.3.1`.
