### ISSUE TITLE
ktor-client 1.3.0 Unable to receive body of request when status code is non-200

### ISSUE THREAD

**Issue by Colins-Git** [ktorio/ktor#1572]
**Ktor Version and Engine Used (client or server and name)**
    implementation("io.ktor:ktor-client-apache:1.3.0")
    implementation("io.ktor:ktor-client-jackson:1.3.0")
    implementation("io.ktor:ktor-client-logging-jvm:1.3.0")

**Describe the bug**
When using the ktor client to make calls to external services and receiving a non-200 response trying to receive the body results in an exception. 

When calling an external service we receive a non-200 error code with a body response detailing why. We receive  the status code and try to log the body of the failed request for additional information. 
We log the results by calling httpResponse.readText(Charsets.UTF_8), however instead of the body text we receive an exception ClientRequestException. 

io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:35)
	at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:96)
	at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:75)
	at io.ktor.client.statement.HttpStatementKt.readText(HttpStatement.kt:158)
	at com.myapp.repository.Person.search(Person.kt:93)

It looks like the DefaultResponseValidation.kt
HttpClientConfig<*>.addDefaultResponseValidation()
throws an exception if the status is not 200. 

**To Reproduce**

 val httpResponse = client.getClient().get<HttpResponse>(searchURI) {
	header("X-Expand-Results", "true")
	header("X-Auth-code", authToken)
}

return when (val httpStatusCode = httpResponse.status) {
	HttpStatusCode.OK -> {
		httpResponse.receive<Person>()
	}
	HttpStatusCode.NotFound -> {
		logger.debug("Person search returned a 404 status")
		/*return*/ null
	}
	else -> {
		val msg = "Person search returned a non-OK status code $httpStatusCode " +
			"with text ${httpResponse.readText(Charsets.UTF_8)}"
		logger.error { msg }
		throw AppException(StatusCode.InternalServerError, msg)
	}
}

**Expected behavior**
We already know the response is a a non-200 and should be able to log the body text along with the response. 

If this is expected and there is a separate way to receive the body of a non-200 response please let us know. 

**Screenshots**

**Comment by cy6erGn0m** [comment]
This is by design behaviour. All non-successful statuses produce an exception (depending on status code).

**Comment by cy6erGn0m** [comment]
All bad status codes get rejected by response validation feature (could be disabled)
https://ktor.io/clients/http-client/features/response-validation.html

**Comment by Colins-Git** [comment]
Thanks for the clarification, i will disable the validation feature and control the bad status codes manually.
