### ISSUE TITLE
Exception after form and session auth 

### ISSUE THREAD

**Issue by Implex1v** [ktorio/ktor#1591]
**Ktor Version and Engine Used (client or server and name)**
Tested on 1.3.0 and 1.2.6

**Describe the bug**
Redirect after form and session login does not work. I am getting an exception.
```
17:11:16.611 [nioEventLoopGroup-4-1] ERROR ktor.application - Unhandled: POST - /login
java.util.NoSuchElementException: No session data found for id c1b0142e44d5e67c
	at io.ktor.sessions.DirectoryStorage.read(DirectoryStorage.kt:49)
	at io.ktor.sessions.CacheStorage$referenceCache$1.invokeSuspend(CacheStorage.kt:15)
	at io.ktor.sessions.CacheStorage$referenceCache$1.invoke(CacheStorage.kt)
	at io.ktor.sessions.ReferenceCache$container$1.invokeSuspend(Cache.kt:50)
	at io.ktor.sessions.ReferenceCache$container$1.invoke(Cache.kt)
	at io.ktor.sessions.BaseCache$getOrCompute$2$1.invokeSuspend(Cache.kt:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:457)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:89)
	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
	at io.ktor.sessions.BaseCache$getOrCompute$2.apply(Cache.kt:36)
	at io.ktor.sessions.BaseCache$getOrCompute$2.apply(Cache.kt:31)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ktor.sessions.BaseCache.getOrCompute(Cache.kt:36)
	at io.ktor.sessions.ReferenceCache.getOrCompute$suspendImpl(Cache.kt:54)
	at io.ktor.sessions.ReferenceCache.getOrCompute(Cache.kt)
	at io.ktor.sessions.BaseTimeoutCache.getOrCompute(Cache.kt:131)
	at io.ktor.sessions.CacheStorage.read(CacheStorage.kt:20)
	at io.ktor.sessions.SessionTrackerById.load(SessionTrackerById.kt:34)
	at io.ktor.sessions.Sessions$Feature$install$1.invokeSuspend(Sessions.kt:60)
	at io.ktor.sessions.Sessions$Feature$install$1.invoke(Sessions.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
	at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:118)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:40)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:30)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**To Reproduce**
```kotlin
import io.ktor.application.call
import io.ktor.application.install
import io.ktor.auth.*
import io.ktor.features.CallLogging
import io.ktor.features.DefaultHeaders
import io.ktor.http.ContentType
import io.ktor.response.respondRedirect
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.post
import io.ktor.routing.routing
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import io.ktor.sessions.*
import java.io.File

fun main() {
    val server = embeddedServer(Netty, port = 8080) {
        install(DefaultHeaders)
        install(CallLogging)
        install(Authentication) {
            session<UserSession>("SESSION_AUTH") {
                challenge {
                    call.respondRedirect("/login")
                }
                validate { session: UserSession ->
                    session
                }
            }

            form("FORM_AUTH") {
                userParamName = "_email"
                passwordParamName = "_password"
                challenge {
                    val errors: Map<Any, AuthenticationFailedCause> = call.authentication.errors
                    when (errors.values.singleOrNull()) {
                        AuthenticationFailedCause.InvalidCredentials -> call.respondRedirect("/login?invalid")
                        AuthenticationFailedCause.NoCredentials -> call.respondRedirect("/login?no")
                        else -> call.respondRedirect("/")
                    }
                }
                validate { credentials ->
                    UserSession(1, "test@acme.org")
                }
            }
        }

        install(Sessions) {
            cookie<UserSession>("TEST", directorySessionStorage(File(".sessions"), cached = true)) {
                cookie.path = "/"
                cookie.extensions["SameSite"] = "lax"
            }
        }

        routing {
            authenticate ("FORM_AUTH") {
                post("/login") {
                    val principal = call.principal<UserSession>()!!
                    call.sessions.set(principal)
                    call.respondRedirect("/")
                }
            }

            get("/login") {
                call.respondText("""<html><body><div>
                    <form action="/login" method="post">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" name="_email" placeholder="example@acme.org"/>
                        <label for="password">Password:</label>
                        <input type="password" class="form-control" id="password" name="_password" />
                        <button type="submit">Login</button>
                    </form>
                </div></body></html>""", contentType = ContentType.Text.Html)
            }

            authenticate("SESSION_AUTH") {
                get("/") {
                    call.respondRedirect("/foo")
                }

                get("/foo") {
                    call.respondText("{}", ContentType.Application.Json)
                }
            }
        }
    }
    server.start(wait = true)
}

class UserSession(val id: Int, val email: String) : Principal
```
Run the server, login and the server will raise a 500. After "failed" login you can visit the index page and you are authenticated. 

**Expected behavior**
The page should be shown instead of an 500 error.

**Comment by cy6erGn0m** [comment]
Should be fixed in 1.3.1

**Comment by cy6erGn0m** [comment]
Feel free to reopen if not

**Comment by Implex1v** [comment]
Thank you very much! I will test it out :)
