### ISSUE TITLE
How to test POST request?

### ISSUE THREAD

**Issue by LookBad** [ktorio/ktor#1807]
Hi!

I wrote a test:
```
object AdminAuthHandlerTest : Spek({
    with(ktorTestEngine()) {
        describe("A sign-in endpoint") {
            lateinit var call: TestApplicationCall
            beforeGroup {
                call = handleRequest(HttpMethod.Post, "/api/admin/auth/sign-in") {
                    addHeader(HttpHeaders.Accept, ContentType.Text.Plain.contentType)
                    addHeader(HttpHeaders.ContentType, ContentType.Application.Json.contentType)
                    setBody(jsonAsString(AdminSignInRequest("admin", "admin123")))
                }
            }
            it("should return 200") {
                println("${call.request.bodyChannel.asString()} ${call.requestHandled}")
                assertThat(call.response.status()).isEqualTo(HttpStatusCode.OK)
            }
            it("should return token in response body") {
                assertThat(call.response.content).contains("token")
            }
            it("should return profile object in response body") {
                assertThat(call.response.content).contains("profile")
            }
            it("should set admin in call") {
                assertThat(call.admin).isNotNull()
            }
        }
    }
})
```
My test fails. In response, I always get 400 code, but I provide correct data in setBody method. When I do the request from Postman (or my client app) with the same data it works correctly. 
```
fun jsonAsString(any: Any): String {
    return Gson().toJson(any)
}
```
I cannot find any information about a similar situation in docs. Do you have any idea what do I wrong?

**Comment by LookBad** [comment]
Do you know where is problem?

**Comment by dmitrievanthony** [comment]
Hi @LookBad, could you please tell me the Ktor version and provide a reproducible snippet? I'm not sure I'm aware of the way you create the application call.

**Comment by LookBad** [comment]
Ok. Catch up: https://gist.github.com/LookBad/89e77c6f5a45fbe386ae89115366cfe0 if you need more files, just let me know.

Body of post method in adminAuthHandler can have only `val request = call.receive<AdminSignInRequest>()` to get this error.

**Comment by LookBad** [comment]
@dmitrievanthony what's up? Did you reproduce my error?

**Comment by dmitrievanthony** [comment]
Hi @LookBad, I still didn't catch the `handleRequest` function so I can't reproduce your code.

**Comment by dmitrievanthony** [comment]
Hi @LookBad,  could you also provide the `ktorTestEngine` function? I can't reproduce the issue without it.

**Comment by dmitrievanthony** [comment]
Well, @LookBad , I definitely need to get the `ktorTestEngine` method because the following code works fine:

```
@KtorExperimentalAPI
@KtorExperimentalLocationsAPI
object AdminAuthHandlerTest : Spek({
    val engine = TestApplicationEngine(createTestEnvironment())
    engine.start()
    engine.application.install(Locations)
    engine.application.routing {
        post<Admin.Auth.SignIn> {
            call.respondText("OK")
        }
    }
    with(engine) {
        describe("A sign-in endpoint") {
            lateinit var call: TestApplicationCall
            beforeGroup {
                call = handleRequest(HttpMethod.Post, "/admin/auth/sign-in") {
                    addHeader(HttpHeaders.Accept, ContentType.Text.Plain.contentType)
                    addHeader(HttpHeaders.ContentType, ContentType.Application.Json.contentType)
                    setBody(jsonAsString(AdminSignInRequest("admin", "admin123")))
                }
            }
            it("should return 200") {
                assertThat(call.response.status()).isEqualTo(HttpStatusCode.OK)
            }
        }
    }
})
```

**Comment by LookBad** [comment]
Ok

```
fun ktorTestEngine() =
    TestApplicationEngine(createTestEnvironment()).apply {
        start(wait = false)
        application.parkkometrModule(true)
    }
```

**Comment by dmitrievanthony** [comment]
It looks like `parkkometrModule` is also some extension function, isn't it?

**Comment by LookBad** [comment]
It'is my application module.

```
@KtorExperimentalAPI
@KtorExperimentalLocationsAPI
@Suppress("unused", "UNUSED_PARAMETER")
fun Application.parkkometrModule(testing: Boolean = false) {
    install(AutoHeadResponse)
    install(Locations)
    install(CORS) {
        anyHost() // @TODO: Don't do this in production if possible. Try to limit it.
        method(HttpMethod.Options)
        method(HttpMethod.Put)
        method(HttpMethod.Post)
        method(HttpMethod.Delete)
        method(HttpMethod.Patch)
        header(HttpHeaders.Authorization)
        allowCredentials = true
        allowNonSimpleContentTypes = true
    }
    install(ContentNegotiation) {
        jackson {
            enable(SerializationFeature.INDENT_OUTPUT)
            dateFormat = DateFormat.getDateInstance()
            findAndRegisterModules()
        }
    }
    install(Authentication) {
        jwt {
            verifier(JwtConfig.verifier)
            realm = "ktor.io"
            validate {
                val accountType = it.payload.getClaim("type").asInt()
                val accountId = it.payload.getClaim("id").asInt()
                if (accountType == Authenticable.TYPE_ADMIN)
                    accountId.let(AdminService()::findAdminById)
                else
                    accountId.let(UserService()::findUserById)
            }
        }
    }
    install(StatusPages) {
        exceptionHandler(this)
    }

    connectWithDatabase()
    routing {
        route("api/") {
            adminAuthHandler()
            userAuthHandler()
            authenticate {
                adminManageHandler()
                profileHandler()
                parkingHandler() }
        }
    }
}
```
I replaced gson with Jackson.

**Comment by dmitrievanthony** [comment]
Well, @LookBad, I used your code and commented the lines I have no source to resolve. The result is here:

```kotlin
package test

import com.fasterxml.jackson.databind.*
import com.google.gson.*
import io.ktor.application.*
import io.ktor.auth.*
import io.ktor.auth.jwt.*
import io.ktor.features.*
import io.ktor.http.*
import io.ktor.jackson.*
import io.ktor.locations.*
import io.ktor.routing.*
import io.ktor.server.testing.*
import io.ktor.util.*
import org.assertj.core.api.Assertions.assertThat
import org.spekframework.spek2.*
import org.spekframework.spek2.style.specification.*
import java.text.*

@KtorExperimentalAPI
@KtorExperimentalLocationsAPI
object AdminAuthHandlerTest : Spek({
    with(ktorTestEngine()) {
        describe("A sign-in endpoint") {
            lateinit var call: TestApplicationCall
            beforeGroup {
                call = handleRequest(HttpMethod.Post, "/api/admin/auth/sign-in") {
                    addHeader(HttpHeaders.Accept, ContentType.Text.Plain.contentType)
                    addHeader(HttpHeaders.ContentType, ContentType.Application.Json.contentType)
                    setBody(jsonAsString(AdminSignInRequest("admin", "admin123")))
                }
            }
            it("should return 200") {
                println("${call.request.bodyChannel} ${call.requestHandled}")
                assertThat(call.response.status()).isEqualTo(HttpStatusCode.OK)
            }
        }
    }
})

fun ktorTestEngine() =
        TestApplicationEngine(createTestEnvironment()).apply {
            start(wait = false)
            application.parkkometrModule(true)
        }

fun jsonAsString(any: Any): String {
    return Gson().toJson(any)
}

@KtorExperimentalAPI
@KtorExperimentalLocationsAPI
@Suppress("unused", "UNUSED_PARAMETER")
fun Application.parkkometrModule(testing: Boolean = false) {
    install(AutoHeadResponse)
    install(Locations)
    install(CORS) {
        anyHost() // @TODO: Don't do this in production if possible. Try to limit it.
        method(HttpMethod.Options)
        method(HttpMethod.Put)
        method(HttpMethod.Post)
        method(HttpMethod.Delete)
        method(HttpMethod.Patch)
        header(HttpHeaders.Authorization)
        allowCredentials = true
        allowNonSimpleContentTypes = true
    }
    install(ContentNegotiation) {
        jackson {
            enable(SerializationFeature.INDENT_OUTPUT)
            dateFormat = DateFormat.getDateInstance()
            findAndRegisterModules()
        }
    }
    install(Authentication) {
        jwt {
//            verifier(JwtConfig.verifier)
            realm = "ktor.io"
//            validate {
//                val accountType = it.payload.getClaim("type").asInt()
//                val accountId = it.payload.getClaim("id").asInt()
//                if (accountType == Authenticable.TYPE_ADMIN)
//                    accountId.let(AdminService()::findAdminById)
//                else
//                    accountId.let(UserService()::findUserById)
//            }
        }
    }
    install(StatusPages) {
//        exceptionHandler(this)
    }

//    connectWithDatabase()
    routing {
        route("api/") {
            adminAuthHandler()
//            userAuthHandler()
            authenticate {
//                adminManageHandler()
//                profileHandler()
//                parkingHandler()
            }
        }
    }
}
```

And it works perfectly well. I'm sure we are on the right way to solve the issue, but to speed the process up could you provide the [minimal, complete and reproducible](https://stackoverflow.com/help/minimal-reproducible-example) examples that demonstrates the issue?

**Comment by LookBad** [comment]
My app: [Archive.zip](https://github.com/ktorio/ktor/files/4559755/Archive.zip).
Ps. I know, I have to clean up the project.

**Comment by LookBad** [comment]
What's up?

**Comment by LookBad** [comment]
ping :)

**Comment by LookBad** [comment]
I have a better message error after I have changed the JRE: 
```
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

**Comment by LookBad** [comment]
@dmitrievanthony what do you think about it?

**Comment by Stexxe** [comment]
@LookBad the root cause is `BadContentTypeFormatException` that is thrown, because of how you add `Content-Type` header in the `app/test/src/handler/api/AdminAuthHandlerTest.kt`:
```kotlin
addHeader(HttpHeaders.ContentType, ContentType.Application.Json.contentType)
```
`contentType` is a property of `ContentType` class that represents the first part of the media type — in your case `application` (from `application/json`). 
To fix this you can replace property access with `toString()` method call:
```kotlin
addHeader(HttpHeaders.ContentType, ContentType.Application.Json.toString())
```

**Comment by LookBad** [comment]
Wow! Thank you! I love it. It should be better documented.
