### ISSUE TITLE
Ktor Client Null Pointer Exception (HTTPS)

### ISSUE THREAD

**Issue by bouff** [ktorio/ktor#1890]
**Ktor Version and Engine Used (client or server and name)**
1.3.1 (client)

**Describe the bug**
When sending a POST request over HTTPS, the ktor client will intermittently throw a NPE.

**To Reproduce**
Not sure exactly how to reproduce... given that the failure is intermittent.  I get this NPE approximately 50% of the time.

**Screenshots**
```
kotlin.KotlinNullPointerException
	at io.ktor.network.tls.TLSClientHandshake.handleServerDone(TLSClientHandshake.kt:327)
	at io.ktor.network.tls.TLSClientHandshake.handleCertificatesAndKeys(TLSClientHandshake.kt:291)
	at io.ktor.network.tls.TLSClientHandshake.negotiate(TLSClientHandshake.kt:155)
	at io.ktor.network.tls.TLSClientHandshake$negotiate$1.invokeSuspend(TLSClientHandshake.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

**Comment by e5l** [comment]
Hi @bouff, could you provide the endpoint you're using?

**Comment by bouff** [comment]
Hi @e5l ,

Apologies for the delay. I set up an Azure Time Series Insights instance that can be used for testing.

Endpoint: https://239da1e6-dccb-4007-a598-4165825affa0.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview

This is useful to reproduce the issue:
```
    fun testMe() {
        val tsiToken = ""
        val httpResponse = try {
            runBlocking {
                HttpClient().use {
                    it.post<HttpResponse> {
                        url("https://239da1e6-dccb-4007-a598-4165825affa0.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview")
                        contentType(ContentType.Application.Json)
                        headers.append("authorization", "Bearer $tsiToken")
                        body = ""
                    }
                }
            }
        } catch (e: Throwable) {
            println("Unable to query TSI: ${e.localizedMessage}\n${stackTraceString(e)}")
            return
        }
        val httpResponseBody = runBlocking { httpResponse.readText() }
        println("TSI query resulted in ${httpResponse.status}: $httpResponseBody")
    }
```
To reproduce the issue, values aren't needed for the authorization header or the request body.

Some of the time I get a 401 (expected in this case) - or the following:
```
Unable to query TSI: null
kotlin.KotlinNullPointerException
	at io.ktor.network.tls.TLSClientHandshake.handleServerDone(TLSClientHandshake.kt:327)
	at io.ktor.network.tls.TLSClientHandshake.handleCertificatesAndKeys(TLSClientHandshake.kt:291)
	at io.ktor.network.tls.TLSClientHandshake.negotiate(TLSClientHandshake.kt:155)
	at io.ktor.network.tls.TLSClientHandshake$negotiate$1.invokeSuspend(TLSClientHandshake.kt)
	(Coroutine boundary)
	at io.ktor.client.engine.cio.CIOEngine.execute(CIOEngine.kt:46)
	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:83)
	at kotlinx.coroutines.DeferredCoroutine.await$suspendImpl(Builders.common.kt:99)
	at io.ktor.client.engine.HttpClientEngine$DefaultImpls.executeWithinCallContext(HttpClientEngine.kt:78)
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(HttpClientEngine.kt:65)
	at io.ktor.client.features.HttpSend$DefaultSender.execute(HttpSend.kt:116)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:79)
	at io.ktor.client.features.DefaultTransformKt$defaultTransformers$1.invokeSuspend(DefaultTransform.kt:37)
	at io.ktor.client.features.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:87)
	at io.ktor.client.features.HttpRequestLifecycle$Feature$install$1.invokeSuspend(HttpRequestLifecycle.kt:34)
	at io.ktor.client.HttpClient.execute(HttpClient.kt:164)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:105)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:44)
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-366">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
