### ISSUE TITLE
Parent coroutine context cancellation sometimes leads to hanging coroutine

### ISSUE THREAD

**Issue by valich** [ktorio/ktor#1947]
**Ktor Version and Engine Used (client or server and name)**
ktor-server-jetty and ktor-websockets 1.3.2
coroutines version 1.3.4

**Describe the bug**
Sometimes my tests hang on post-test test job cancellation. That job contains both client and server coroutine scopes/jobs as decdendants.

Coroutines dump (printed after test timeout) gives this:
```
[15:17:55] :			 [gant] [junit] Coroutine "jetty-call-handler#6995":StandaloneCoroutine{Cancelling}@258a8584, state: SUSPENDED
[15:17:55] :			 [gant] [junit] 	at io.ktor.server.jetty.JettyKtorHandler$handle$2.invokeSuspend(JettyKtorHandler.kt:125)
[15:17:55] :			 [gant] [junit] 	at    (Coroutine creation stacktrace. ( )
[15:17:55] :			 [gant] [junit] 	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:116)
[15:17:55] :			 [gant] [junit] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
[15:17:55] :			 [gant] [junit] 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
[15:17:55] :			 [gant] [junit] 	at io.ktor.server.jetty.JettyKtorHandler.handle(JettyKtorHandler.kt:85)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.server.Server.handle(Server.java:500)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
[15:17:55] :			 [gant] 
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
[15:17:55] :			 [gant] [junit] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)

```

**To Reproduce**
Unfortunately, the bug can't be reproduced locally even with the existing tests, happens only on CI. No minimal sample yet.

**Expected behavior**
No suspended coroutines after a parent-induced cancellation.

**Comment by e5l** [comment]
Hi @valich, thanks for the report.
Could you file a snippet to start the investigation?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-339">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
