### ISSUE TITLE
MySessionSerializer<T>.serialize() *must* return string with trailing \n

### ISSUE THREAD

**Issue by pmorch** [ktorio/ktor#1965]
**Ktor Version and Engine Used (client or server and name)**

ktor_version=1.3.2
kotlin_version=1.3.70

**Describe the bug**

When deserializing, `io.ktor.utils.io.ByteReadChannelKt.readUTF8Line()` is called and that tries to reads one char too far unless the string returned from `MySessionSerializer<T>.serialize()` has a trailing newline.

**To Reproduce**

```
class SerializableSessionSerializer<T>() : SessionSerializer<T> {
    override fun serialize(session: T): String {
        val foo: OAuthSessionData
        val bo = ByteArrayOutputStream()
        val so = ObjectOutputStream(bo)
        so.writeObject(session)
        so.flush()
        val enc = Base64.getEncoder().encodeToString(bo.toByteArray())
        // return enc + "\n"
        return enc
    }

    override fun deserialize(text: String): T {
        val b: ByteArray = Base64.getDecoder().decode(text)
        val s = b.toString()
        val bi = ByteArrayInputStream(b)
        val si = ObjectInputStream(bi)
        return si.readObject() as T
    }
}
...
    install(Sessions) {
        cookie<MySessionData>("mycookie", storage = SessionStorageMemory()) {
            serializer = SerializableSessionSerializer<MySessionData>()
        }
    }

```

**Expected behavior**

I expected that a valid serialized string would've been fine.

**Stack trace**
As seen in the console:
```
2020-06-23 00:48:34.721 [nioEventLoopGroup-4-1] ERROR Application - Unhandled: GET - /
java.lang.IllegalArgumentException: newPosition > limit: (9105 > 9104)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
	at java.base/java.nio.Buffer.position(Buffer.java:293)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1086)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:262)
	at io.ktor.utils.io.charsets.UTFKt.decodeUTF8Line_array(UTF.kt:661)
	at io.ktor.utils.io.charsets.UTFKt.decodeUTF8Line(UTF.kt:36)
	at io.ktor.utils.io.ByteBufferChannel$readUTF8LineToUtf8Suspend$2.invokeSuspend(ByteBufferChannel.kt:2120)
	at io.ktor.utils.io.ByteBufferChannel$readUTF8LineToUtf8Suspend$2.invoke(ByteBufferChannel.kt)
	at io.ktor.utils.io.ByteBufferChannel.lookAheadSuspend$suspendImpl(ByteBufferChannel.kt:1877)
	at io.ktor.utils.io.ByteBufferChannel.lookAheadSuspend(ByteBufferChannel.kt)
	at io.ktor.utils.io.ByteBufferChannel.readUTF8LineToUtf8Suspend(ByteBufferChannel.kt:2116)
	at io.ktor.utils.io.ByteBufferChannel.readUTF8LineToAscii(ByteBufferChannel.kt:2056)
	at io.ktor.utils.io.ByteBufferChannel.readUTF8LineTo$suspendImpl(ByteBufferChannel.kt:2144)
	at io.ktor.utils.io.ByteBufferChannel.readUTF8LineTo(ByteBufferChannel.kt)
	at io.ktor.utils.io.ByteBufferChannel.readUTF8Line$suspendImpl(ByteBufferChannel.kt:2148)
	at io.ktor.utils.io.ByteBufferChannel.readUTF8Line(ByteBufferChannel.kt)
	at io.ktor.utils.io.ByteReadChannelKt.readUTF8Line(ByteReadChannel.kt:223)
	at io.ktor.sessions.SessionTrackerById$load$2.invokeSuspend(SessionTrackerById.kt:35)
	at io.ktor.sessions.SessionTrackerById$load$2.invoke(SessionTrackerById.kt)
	at io.ktor.sessions.SessionStorageMemory.read(SessionStorageMemory.kt:34)
	at io.ktor.sessions.SessionTrackerById.load(SessionTrackerById.kt:34)
	at io.ktor.sessions.SessionsKt.receiveSessionData(Sessions.kt:205)
	at io.ktor.sessions.Sessions$Feature$install$1.invokeSuspend(Sessions.kt:59)
	at io.ktor.sessions.Sessions$Feature$install$1.invoke(Sessions.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:107)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:40)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:30)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-332">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
@pmorch I cannot reproduce it with Ktor 1.6.0.
