### ISSUE TITLE
watchUrls fail if build/classes/java/main is missing

### ISSUE THREAD

**Issue by magnuschatt** [ktorio/ktor#217]
If you have no java source files the **build/classes/java/main** won't exist. When you run your ktor application you get this error: 

```
Exception in thread "main" java.nio.file.NoSuchFileException: D:\wadaxw\awdawdx\awdad\awdaw\awdawd\build\classes\java\main
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.jetbrains.ktor.host.ApplicationHostEnvironmentReloading.watchUrls(ApplicationHostEnvironmentReloading.kt:204)
	at org.jetbrains.ktor.host.ApplicationHostEnvironmentReloading.createClassLoader(ApplicationHostEnvironmentReloading.kt:153)
	at org.jetbrains.ktor.host.ApplicationHostEnvironmentReloading.createApplication(ApplicationHostEnvironmentReloading.kt:115)
	at org.jetbrains.ktor.host.ApplicationHostEnvironmentReloading.start(ApplicationHostEnvironmentReloading.kt:219)
	at org.jetbrains.ktor.netty.NettyApplicationHost.start(NettyApplicationHost.kt:35)
	at org.jetbrains.ktor.netty.NettyApplicationHost.start(NettyApplicationHost.kt:15)
	at org.jetbrains.ktor.host.ApplicationHost$DefaultImpls.start$default(ApplicationHost.kt:20)
	at org.jetbrains.ktor.netty.DevelopmentHost.main(CommandLine.kt:9)
```

**Comment by orangy** [comment]
What's runtime classpath for the application? Can it be gradle adding non-existing folders there? Said that, I think we indeed should check if folders from classpath exist.

**Comment by magnuschatt** [comment]
> What's runtime classpath for the application? Can it be gradle adding non-existing folders there?

Not sure what you mean, but I've created a quick fix in my gradle file like so:
```
task createJavaClassesMainDir() { doLast { new File("$buildDir/classes/java/main").mkdirs() } }
compileKotlin.finalizedBy(createJavaClassesMainDir)
```

**Comment by chrisjenx** [comment]
I noticed this when using `gretty` but might be gradle. How do you run your app @magnuschatt

**Comment by magnuschatt** [comment]
I'm using Gradle (with the 'application' plugin) and IntelliJ :)

**Comment by chrisjenx** [comment]
Yeah, so I'm guessing it's the Gradle plugin not creating the Java folder
if there are no Java classes. Hopefully an easy fix.

**Comment by cy6erGn0m** [comment]
Should be fixed in current `develop` branch
