### ISSUE TITLE
Ktor/Netty hang up while Ktor/Jetty is fine

### ISSUE THREAD

**Issue by kobe2000** [ktorio/ktor#2378]
Hi

I am doing stress test to a ktor app, it is running under Centos 7. The ktor version is `1.5.2`.

First I use Netty as engine, but found the server would die after some times of client reconnection, I used jcmd to view the jvm threads and found a lot of TIMED_WAITING dispatcher thread like following:

```
"DefaultDispatcher-worker-65" #321 daemon prio=5 os_prio=0 tid=0x00007f411c024000 nid=0xeaf waiting on condition [0x00007f3f1e9e8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at io.ktor.utils.io.jvm.javaio.DefaultParking.park(Pollers.kt:44)
	at io.ktor.utils.io.jvm.javaio.BlockingAdapter.parkingLoop(Blocking.kt:255)
	at io.ktor.utils.io.jvm.javaio.BlockingAdapter.submitAndAwait(Blocking.kt:235)
	at io.ktor.utils.io.jvm.javaio.BlockingAdapter.submitAndAwait(Blocking.kt:206)
	at io.ktor.utils.io.jvm.javaio.InputAdapter.read(Blocking.kt:67)
	- locked <0x0000000081baf4c0> (a io.ktor.utils.io.jvm.javaio.InputAdapter)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x0000000081baf4a8> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1291)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:816)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at io.ktor.gson.GsonConverter$convertForReceive$2.invokeSuspend(GsonSupport.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

After hours debuging, finally I changed the ktor engine to Jetty, and the server never died again, but report following exception:

```
com.google.gson.JsonIOException: io.ktor.util.cio.ChannelReadException: Cannot read from a servlet input stream
        at com.google.gson.internal.Streams.parse(Streams.java:62)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:870)
        at io.ktor.gson.GsonConverter$convertForReceive$2.invokeSuspend(GsonSupport.kt:46)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: io.ktor.util.cio.ChannelReadException: Cannot read from a servlet input stream
        at io.ktor.server.servlet.ServletReader.wrapException(ServletReader.kt:97)
        at io.ktor.server.servlet.ServletReader.onError(ServletReader.kt:74)
        at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:899)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection$AsyncReadCallback.failed(HttpConnection.java:679)
        at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140)
        at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407)
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
        at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

I think there's maybe some relation, please check these log information

**Comment by JReverse** [comment]
Same issue here 👍

**Comment by e5l** [comment]
Hey @kobe2000, the issues on GitHub are closed cause they are hard to manage and plan. Please consider reopening this issue on YT: https://github.com/ktorio/ktor/issues/new/choose

**Comment by navrocky** [comment]
Same issue with Ktor 1.6.8 and Netty
