### ISSUE TITLE
500 response for how java.net.URL() queries the connection.

### ISSUE THREAD

**Issue by shafirov** [ktorio/ktor#255]
I have a code like this:
`URL("$hostUrl/settings.json").readText()` where hostUrl is served by Ktor

, which results in exception:
`io.ktor.http.BadContentTypeFormatException: Bad Content-Type format: *
	at io.ktor.http.ContentType$Companion$parse$1.invoke(ContentTypes.kt:65)
	at io.ktor.http.ContentType$Companion$parse$1.invoke(ContentTypes.kt:61)
	at io.ktor.http.HeaderValueWithParameters$Companion.parse(HeaderValueWithParameters.kt:25)
	at io.ktor.http.ContentType$Companion.parse(ContentTypes.kt:62)
	at io.ktor.http.HttpHeaderValueParserKt$parseAndSortContentTypeHeader$$inlined$thenBy$1.compare(Comparisons.kt:291)
	at io.ktor.http.HttpHeaderValueParserKt$parseAndSortContentTypeHeader$$inlined$thenByDescending$1.compare(Comparisons.kt:158)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at kotlin.collections.ArraysKt___ArraysKt.sortWith(_Arrays.kt:13685)
	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:866)
	at io.ktor.http.HttpHeaderValueParserKt.parseAndSortContentTypeHeader(HttpHeaderValueParser.kt:24)
	at io.ktor.routing.HttpAcceptRouteSelector.evaluate(RouteSelector.kt:316)
	at io.ktor.routing.RoutingResolveContext.resolve$ktor_server_core(RoutingResolve.kt:73)
	at io.ktor.routing.RoutingResolveContext.resolve$ktor_server_core(RoutingResolve.kt:77)
	at io.ktor.routing.RoutingResolveContext.resolve$ktor_server_core(RoutingResolve.kt:77)
	at io.ktor.routing.RoutingResolveContext.resolve(RoutingResolve.kt:60)
	at io.ktor.routing.Routing.interceptor(Routing.kt:16)
	at io.ktor.routing.Routing$Feature$install$1.doResume(Routing.kt:59)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:44)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:31)
	at io.ktor.features.StatusPages.intercept(StatusPages.kt:55)
	at io.ktor.features.StatusPages$Feature$install$1.doResume(StatusPages.kt:84)
	at io.ktor.features.StatusPages$Feature$install$1.invoke(StatusPages.kt)
	at io.ktor.features.StatusPages$Feature$install$1.invoke(StatusPages.kt:78)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:31)
	at io.ktor.features.CallLogging$Feature$install$1.doResume(CallLogging.kt:42)
	at io.ktor.features.CallLogging$Feature$install$1.invoke(CallLogging.kt)
	at io.ktor.features.CallLogging$Feature$install$1.invoke(CallLogging.kt:34)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:31)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:16)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.doResume(DefaultEnginePipeline.kt:66)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:31)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:16)
	at io.ktor.server.jetty.JettyKtorHandler$handle$2.doResume(JettyKtorHandler.kt:77)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
`

**Comment by orangy** [comment]
Thank you for submitting an issue :) From stack trace, it looks like there is `HttpAcceptRouteSelector` installed via `accept` routing builder function. It tries to parse an `Accept:` header, which seems to be just `*`, and not `*/*`. According to https://tools.ietf.org/html/rfc7231#section-5.3.2 accept header with such value is not allowed. I will check if URL sends such header by default, it sounds strange.

**Comment by orangy** [comment]
Indeed, it does in `HttpURLConnection`… Weird.
```
this.requests.setIfNotSet("Accept", "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2");
```

**Comment by orangy** [comment]
I think we have to handle single `*` as `*/*` at this point. Demanding every `URL` class user to specify explicit `Accept` header would not be very user friendly…

**Comment by orangy** [comment]
Fixed
