### ISSUE TITLE
Log a warning about installing second handler for the same route

### ISSUE THREAD

**Issue by noncom** [ktorio/ktor#268]
Under certain circumstances it happens that Ktor attempts to send a double response on a HTTP  request.

A sample repository with an MRC: https://github.com/noncom/ktor-double-response-issue

Steps to reproduce: the `KtorTest` main object contains 3 samples of the `routing` structure. Comment/uncomment the samples to get the behavior described in the corresponding comments.

The issue: upon the attempt to access the `localhost:8080` address with the first routing sample being active, Ktor gives the following error:

```
13:45:29.158 [nettyCallPool-4-1] ERROR ktor.application - 200 OK: GET - /
io.ktor.server.engine.BaseApplicationResponse$ResponseAlreadySentException: Response has already been sent
	at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.doResume(BaseApplicationResponse.kt:30)
	at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt)
	at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt:14)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:31)
	at io.ktor.pipeline.PipelineContext.proceedWith(PipelineContext.kt:20)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.doResume(DefaultTransform.kt:15)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:31)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:16)
	at io.ktor.content.StaticContentKt$defaultResource$1.doResume(StaticContent.kt:150)
	at io.ktor.content.StaticContentKt$defaultResource$1.invoke(StaticContent.kt)
	at io.ktor.content.StaticContentKt$defaultResource$1.invoke(StaticContent.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:31)
	at io.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:123)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

What is expected: Ktor should not attempt to send more than one response per request.

**Comment by orangy** [comment]
You have two handlers installed for the same route `/`, one via `get("/") { Hello.respond(call) }` and second with `defaultResource("index.html")`. They are both executed, and second tries to send a response after it has already been sent by first. 

We need to design what to do in such a case.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-811">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Hey, @noncom. I'm not sure we can do anything about it, the routing table is generated in runtime and there are valid use cases for that. Maybe we can try to make such stuff as inspection in the IDE. I will create a separate issue.

**Comment by e5l** [comment]
https://youtrack.jetbrains.com/issue/KTOR-2826
