### ISSUE TITLE
Support BigDecimal in feature locations

### ISSUE THREAD

**Issue by rickygao** [ktorio/ktor#362]
When I add a BigDecimal property into class annotated by `Location` and use it for routing, 
```
@Location(path = "/university/name/{name}/location/{location}/latitude/{latitude}/longitude/{longitude}/")
class UniversityPut(
        val name: String,
        val location: String,
        val latitude: String,
        val longitude: BigDecimal
)

private fun Route.universityPut() = put<UniversityPut> { university -> ...
```
An exception is thrown.
```
io.ktor.util.DataConversionException: Type class java.math.BigDecimal is not supported in default data conversion service
	at io.ktor.util.DefaultConversionService.convert(ConversionService.kt:61)
	at io.ktor.util.DefaultConversionService.fromValues(ConversionService.kt:45)
	at io.ktor.locations.Locations.createFromParameters(Locations.kt:55)
	at io.ktor.locations.Locations.create(Locations.kt:40)
	at io.ktor.locations.Locations.resolve(Locations.kt:131)
	at io.ktor.locations.Locations.resolve(Locations.kt:126)
	at io.ktor.locations.LocationKt$handle$1.doResume(Location.kt:89)
	at io.ktor.locations.LocationKt$handle$1.invoke(Location.kt)
	at io.ktor.locations.LocationKt$handle$1.invoke(Location.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.routing.Routing.executeResult(Routing.kt:93)
	at io.ktor.routing.Routing.interceptor(Routing.kt:19)
	at io.ktor.routing.Routing$Feature$install$1.doResume(Routing.kt:60)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:45)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.features.ContentNegotiation$Feature$install$1.doResume(ContentNegotiation.kt:59)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt:49)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.features.CallLogging$Feature$install$1.doResume(CallLogging.kt:69)
	at io.ktor.features.CallLogging$Feature$install$1.invoke(CallLogging.kt)
	at io.ktor.features.CallLogging$Feature$install$1.invoke(CallLogging.kt:61)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.doResume(DefaultEnginePipeline.kt:66)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.doResume(NettyApplicationCallHandler.kt:27)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt:10)
	at kotlinx.coroutines.experimental.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.experimental.CoroutineStart.invoke(CoroutineStart.kt:113)
	at kotlinx.coroutines.experimental.AbstractCoroutine.start(AbstractCoroutine.kt:161)
	at kotlinx.coroutines.experimental.BuildersKt.launch(Builders.kt:65)
	at kotlinx.coroutines.experimental.BuildersKt.launch$default(Builders.kt:58)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:22)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:16)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by orangy** [comment]
Well, there is clear error message: "io.ktor.util.DataConversionException: Type class java.math.BigDecimal is not supported in default data conversion service"

As a workaround, you can provide your own data conversion service.

**Comment by soywiz** [comment]
Check this page for adding custom converters:
https://ktor.io/features/data-conversion.html#adding-converters
