### ISSUE TITLE
Deserializing generic types with GSON for ktor client

### ISSUE THREAD

**Issue by fegol** [ktorio/ktor#365]
See this [code](https://gist.github.com/fegol/f3ead52ac39e4e38f627c549840b8eee)
When i run this sample, i get an exception:
Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Lru.fegol.telebot.sample.User;
	at ru.fegol.telebot.sample.SampleKt$main$2.doResume(Sample.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:241)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:182)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:172)
	at ru.fegol.telebot.sample.SampleKt.main(Sample.kt:39)

**Comment by JLLeitschuh** [comment]
@e5l I just ran into this issue.

Is there a workaround available in `0.9.2` that I can use?

**Comment by e5l** [comment]
fix is done and will be available soon(approximately in next release).

**Comment by mkobit** [comment]
Related/duplicate issue: https://github.com/ktorio/ktor/issues/346

**Comment by e5l** [comment]
Fixed in `master`
