### ISSUE TITLE
Basic Authentication provider fails on invalid Authorization header

### ISSUE THREAD

**Issue by fabianishere** [ktorio/ktor#414]
Routes protected behind the Basic Authentication Provider can fail when an invalid Authorization header is sent with the request. 

For example, sending a request with the header `Authorization: Bearer some-token` to a Basic-protected endpoint will crash the request handler, respond with a 500 Internal Server Error and spit the following error in the console:

> java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.ktor.auth.BasicAuthKt.basicAuthenticationCredentials(BasicAuth.kt:75)
       ...

Is this expected behaviour? I have added two test cases and a possible fix at 1d56c52  on the `bug/auth-basic-invalid-scheme` branch of my fork.

**Comment by fabianishere** [comment]
@cy6erGn0m Do you want me to split the changes into two commits perhaps?

**Comment by fabianishere** [comment]
See #415 for the pull request.
