### ISSUE TITLE
BodyLengthIsTooLong exception is thrown when page is "sizy"

### ISSUE THREAD

**Issue by coder82** [ktorio/ktor#431]
[see image here](https://ibb.co/co3W2o)

See the image, expected is one smaller than actual... in this case

`Exception in thread "io-thread-1 @io-dispatcher-executor-1#2 @coroutine#30" io.ktor.server.engine.BaseApplicationResponse$BodyLengthIsTooLong: Body.size is too long. Expected 731448
	at io.ktor.server.engine.BaseApplicationResponse.ensureLength(BaseApplicationResponse.kt:178)
	at io.ktor.server.engine.BaseApplicationResponse.access$ensureLength(BaseApplicationResponse.kt:16)
	at io.ktor.server.engine.BaseApplicationResponse$respondFromChannel$2.doResume(BaseApplicationResponse.kt:173)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
	at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:78)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:73)
Exception in thread "io-thread-1 @io-dispatcher-executor-1#2 @coroutine#35" io.ktor.server.engine.BaseApplicationResponse$BodyLengthIsTooLong: Body.size is too long. Expected 731448
	at io.ktor.server.engine.BaseApplicationResponse.ensureLength(BaseApplicationResponse.kt:178)
	at io.ktor.server.engine.BaseApplicationResponse.access$ensureLength(BaseApplicationResponse.kt:16)
	at io.ktor.server.engine.BaseApplicationResponse$respondFromChannel$2.doResume(BaseApplicationResponse.kt:173)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
	at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:78)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:73)

io.ktor.server.engine.BaseApplicationResponse$BodyLengthIsTooLong: Body.size is too long. Expected 731448

	at io.ktor.server.engine.BaseApplicationResponse.ensureLength(BaseApplicationResponse.kt:178)
	at io.ktor.server.engine.BaseApplicationResponse.access$ensureLength(BaseApplicationResponse.kt:16)
	at io.ktor.server.engine.BaseApplicationResponse$respondFromChannel$2.doResume(BaseApplicationResponse.kt:173)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
	at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:78)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:73)`

**Comment by e5l** [comment]
Hi, @coder82, thanks for the report. 
Could you provide some code sample? 

If you provide `OutgoingContent` by hand, please make sure that field contentLength is filled properly.

**Comment by coder82** [comment]
Hi, it happens sporadically, but more often if the file is very big, like for example 100-300Mbytes.
And it happens just in a test where, all I am doing is I am checking if my server is live and if logs are produced. Unfortunately the log file happens to be big during testing, hence the exception pops.

Here are some more infos, really simple:
Testing:

`    @Test
    fun testIsLive() {
        withTestApplication(Application::mainModule) {
            with(handleRequest(HttpMethod.Get, "/$ctx/")) {
                assertEquals(HttpStatusCode.OK, response.status())
            }
            with(handleRequest(HttpMethod.Get, "/$ctx/logs/")) {
                assertEquals(HttpStatusCode.OK, response.status())
                DateTimeFormatter.BASIC_ISO_DATE
            }
            with(handleRequest(HttpMethod.Get, "/$ctx/logs/logs_${LocalDate.now().format(DateTimeFormatter.ISO_LOCAL_DATE)}.html")) {
                assertEquals(HttpStatusCode.OK, response.status())
            }
        }
    }`

`
fun Route.handleStatic() {
    static("$ctx/logs") {
        files("logs") // in case you want to access historical logs
    }
}
`

**Comment by coder82** [comment]
I temporary reduced the size of my logs, but this problem will happen again sooner or later.
I am developing on Windows 10.

**Comment by e5l** [comment]
Could you reproduce the problem on `0.9.4-alpha-2`?

**Comment by e5l** [comment]
Can't reproduce. Please reopen if the problem occurs.
