### ISSUE TITLE
basic auth handler can choke when authScheme is not "Basic"

### ISSUE THREAD

**Issue by mkporwit** [ktorio/ktor#432]
In trying to register multiple auth handlers for a single route (one basic, one jwt), I encountered an issue where if I sent a request to our login endpoint with a Bearer token, basicAuthenticationCredentials() would choke when it tried to base64 decode the token. It already knows that the authScheme is not Basic, so it should just return null instead of trying to parse the payload.

**Comment by mkporwit** [comment]
```✔ [mkporwit@mkporwit-mbpro:~/work/auth] [enable-openid|✚ 3] $ curl 'http://localhost:8080/login' -H 'accept: application/json' -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImlCakwxUmNxemhpeTRmcHhJeGRacW9oTTJZayJ9.eyJhdWQiOiIxYjk4N2YwNy01OThkLTRmMjgtYWU1My0zZGIzYjYyY2U4NjUiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vYjVjYTNjZGEtYWNkMS00NjE2LTg3NmMtZWQyZWQ2NGZlNjU3L3YyLjAiLCJpYXQiOjE1MjgyNDIxMjEsIm5iZiI6MTUyODI0MjEyMSwiZXhwIjoxNTI4MjQ2MDIxLCJhaW8iOiJBVFFBeS84SEFBQUExbm5kRUdkZ1NDUThZV0xucGpiOGJ3UklVZnZaVFZHVVF6U2tHMndtUEJWY0JWZXpDcGxRclBqSjQxYzQ0UGJQIiwiYXpwIjoiZTg5NDIzYTItMWYzMS00YWViLWJiOWQtYjVmYzRjODU2OTAxIiwiYXpwYWNyIjoiMSIsIm5hbWUiOiJNYXJjaW4gS3J6eXN6dG9mIFBvcndpdCIsIm9pZCI6IjEzNDIwNDgxLTNjODMtNDc4YS1hMjExLTNiNTQzMGRhNzdhOSIsInByZWZlcnJlZF91c2VybmFtZSI6Im1rcEBob3lsdS5jb20iLCJzY3AiOiJhY2Nlc3NfYXNfdXNlciIsInN1YiI6Ik1kWFJ1WXotbi1DajlRVkxLSTZMa01qWmh2VHpCdTRZaXJsNFRFWmdfcnciLCJ0aWQiOiJiNWNhM2NkYS1hY2QxLTQ2MTYtODc2Yy1lZDJlZDY0ZmU2NTciLCJ1dGkiOiJ1bnpjYWVlLTEwNnlPNkF2VE1JWkFBIiwidmVyIjoiMi4wIn0.eowOGUDUwqiprAODZoIfHOG18V5FcofwBWQXnVbE3ldgiQ1lMRqBNJmIxo3TQ4N0YXcQbavi-3ZX2luEY81GPDYzjq0Ms9unL_KhBpwmOpBmfP-y3eSkEHRkoqoKrEy1Y-1PJgXKQtbIcQO0lDzV5bYPQkgK1AqLKurc38vI_dZShNTVN-0F3hlMM-cT2zjbcefRDYW3Xbj5kTKOpzk-6goJobj7GRYah5Hc4oaoliBwqAZdALynlpO1stFJq75rOjiT9kjd8oyEhsFSevkaBqbsV2gnhJGsPf4f65ajvL_4r72Q5GJbVLiFsK1jMGTJ1JuTtR_qu3HiXLXsWVE6Pw'
Illegal base64 character 2e```

blows up with the following stack trace: 
```2018-06-05 17:11:42.976 [pool-1-thread-1] ERROR Auth - java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.ktor.auth.BasicAuthKt.basicAuthenticationCredentials(BasicAuth.kt:75)
	at io.ktor.auth.BasicAuthKt$basic$1.doResume(BasicAuth.kt:39)
	at io.ktor.auth.BasicAuthKt$basic$1.invoke(BasicAuth.kt)
	at io.ktor.auth.BasicAuthKt$basic$1.invoke(BasicAuth.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.auth.Authentication.processAuthentication(Authentication.kt:163)
	at io.ktor.auth.Authentication$interceptPipeline$2.doResume(Authentication.kt:89)
	at io.ktor.auth.Authentication$interceptPipeline$2.invoke(Authentication.kt)
	at io.ktor.auth.Authentication$interceptPipeline$2.invoke(Authentication.kt:13)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.routing.Routing.executeResult(Routing.kt:100)
	at io.ktor.routing.Routing.interceptor(Routing.kt:25)
	at io.ktor.routing.Routing$Feature$install$1.doResume(Routing.kt:66)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:51)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.features.ContentNegotiation$Feature$install$1.doResume(ContentNegotiation.kt:60)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt:50)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.features.StatusPages.intercept(StatusPages.kt:55)
	at io.ktor.features.StatusPages$Feature$install$1.doResume(StatusPages.kt:84)
	at io.ktor.features.StatusPages$Feature$install$1.invoke(StatusPages.kt)
	at io.ktor.features.StatusPages$Feature$install$1.invoke(StatusPages.kt:78)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.metrics.Metrics$Feature$install$1.doResume(Metrics.kt:44)
	at io.ktor.metrics.Metrics$Feature$install$1.invoke(Metrics.kt)
	at io.ktor.metrics.Metrics$Feature$install$1.invoke(Metrics.kt:22)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.features.CallLogging$Feature$install$1.doResume(CallLogging.kt:69)
	at io.ktor.features.CallLogging$Feature$install$1.invoke(CallLogging.kt)
	at io.ktor.features.CallLogging$Feature$install$1.invoke(CallLogging.kt:61)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.doResume(DefaultEnginePipeline.kt:66)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.server.jetty.JettyKtorHandler$handle$2.doResume(JettyKtorHandler.kt:61)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by mkporwit** [comment]
This is in 0.9.3-alpha-1

**Comment by mkporwit** [comment]
Never mind, looks like you guys caught it in 0.9.3-alpha-2. Good job 👍
