### ISSUE TITLE
NoSuchMethodError when trying to use Kotlinx.html's call.respondHtml() 

### ISSUE THREAD

**Issue by legzo** [ktorio/ktor#444]
Hi, 

I was trying to run [this sample](http://ktor.io/features/templates/html-dsl.html) but I have an exception stating that there is a missing method somewhere under the hood.

Here is the stack :

```
2018-06-15 17:41:52.287 [nettyCallPool-4-1] ERROR ktor.application - 200 OK: GET - /home
java.lang.NoSuchMethodError: kotlinx.html.stream.StreamKt.appendHTML$default(Ljava/lang/Appendable;ZILjava/lang/Object;)Lkotlinx/html/TagConsumer;
	at io.ktor.html.HtmlContent.writeTo(RespondHtml.kt:30)
	at io.ktor.server.engine.BaseApplicationResponse$respondWriteChannelContent$2.doResume(BaseApplicationResponse.kt:141)
	at io.ktor.server.engine.BaseApplicationResponse$respondWriteChannelContent$2.invoke(BaseApplicationResponse.kt)
	at io.ktor.server.engine.BaseApplicationResponse$respondWriteChannelContent$2.invoke(BaseApplicationResponse.kt:16)
	at io.ktor.cio.ReadersKt.use(Readers.kt:36)
```

and my code is as follows, pretty similar to the sample : 

```kotlin
fun main(args: Array<String>) {
    embeddedServer(Netty, 8888, watchPaths = listOf("MyApp"), module = Application::module).start()
}

fun Application.module() {

    routing {
        
        get("/home") {

            call.respondHtml {
                head {
                    title { +"Async World" }
                }
                body {

                    h1 {
                        +"Title"
                    }
                    
                }
            }

        }
    }
}
```

I have tried rendering the HTML with `createHTML().html` and returning it with `call.respondText()` and it works OK, but it seems that there is a mismatch somewhere when using `respondHtml`

The versions I use : 

```
    def ktor_version = "0.9.2"
    def kotlinx_html_version = "0.6.10"
```

Thanks !

**Comment by cy6erGn0m** [comment]
This is caused by broken binary compatibility in kotlinx.html. See Kotlin/kotlinx.html#91
