### ISSUE TITLE
[client]: Sendig a get request result in IncompatibleClassChangeError

### ISSUE THREAD

**Issue by devJochIm** [ktorio/ktor#450]
Hello, 
I ran into a Problem when sending a get request. Most of the time the error occurs bevor submit the request, so the is not a incoming request on my server.
`Exception in thread "main" java.lang.IncompatibleClassChangeError
	at kotlinx.coroutines.experimental.Job$DefaultImpls.invokeOnCompletion$default(Job.kt:337)
	at io.ktor.client.engine.apache.ApacheHttpRequestKt.sendRequest(ApacheHttpRequest.kt:75)
	at io.ktor.client.engine.apache.ApacheHttpRequest.execute(ApacheHttpRequest.kt:34)
	at io.ktor.client.engine.apache.ApacheEngine.execute(ApacheEngine.kt:20)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$2.doResume(HttpClient.kt:57)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$2.invoke(HttpClient.kt)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$2.invoke(HttpClient.kt:17)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.doResume(HttpClient.kt:37)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invoke(HttpClient.kt)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invoke(HttpClient.kt:17)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at io.ktor.client.HttpClient.execute(HttpClient.kt:98)
	at io.ktor.client.call.HttpClientCallKt.call(HttpClientCall.kt:63)
	at io.ktor.client.call.UtilsKt.call(utils.kt:17)
	at Server.StocktakingClient$start$htmlContent$1.doResume(StocktakingClient.kt:97)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:148)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:82)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:58)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Unknown Source)
	at Server.StocktakingClient.start(StocktakingClient.kt:40)
	at Server.StocktakingClientKt.main(StocktakingClient.kt:74)`

Same problem with Apache and Jetty.
Ktor version: '0.9.2'
Kotlin version: '1.2.41'
OS: Windows 10

**Comment by cy6erGn0m** [comment]
Fixed in 0.9.3
