### ISSUE TITLE
RawSockets+TLS: ClosedReceiveChannelException: EOF: one byte required

### ISSUE THREAD

**Issue by soywiz** [ktorio/ktor#454]
This exception is displayed in the console, though **the code executes normally**:

```kotlin
import io.ktor.network.selector.*
import io.ktor.network.sockets.*
import io.ktor.network.util.*
import kotlinx.coroutines.experimental.*
import kotlinx.coroutines.experimental.io.*
import io.ktor.network.tls.*
import kotlinx.io.core.*

object TlsRawSocket {
    @JvmStatic
    fun main(args: Array<String>) {
        runBlocking {
            val selectorManager = ActorSelectorManager(ioCoroutineDispatcher)
            val socket = aSocket(selectorManager).tcp().connect("www.google.com", port = 443).tls()
            val write = socket.openWriteChannel()
            val LINE = "\r\n"
            write.writeStringUtf8("GET / HTTP/1.1${LINE}Host: www.google.com${LINE}Connection: close${LINE}${LINE}")
            write.flush()
            println(socket.openReadChannel().readRemaining().readBytes().toString(Charsets.UTF_8))
        }
    }
}
```

```
Exception in thread "io-thread-2" kotlinx.coroutines.experimental.channels.ClosedReceiveChannelException: EOF: one byte required
	at kotlinx.coroutines.experimental.io.ByteBufferChannel.readByteSuspend(ByteBufferChannel.kt:667)
	at kotlinx.coroutines.experimental.io.ByteBufferChannel.readByte(ByteBufferChannel.kt:661)
	at io.ktor.network.tls.ParserKt.readTLSRecord(Parser.kt:16)
	at io.ktor.network.tls.TLSClientHandshake$input$1.doResume(TLSClientHandshake.kt:57)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
	at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:78)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:148)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:82)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:58)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:73)

HTTP/1.1 200 OK
Date: Thu, 28 Jun 2018 13:44:44 GMT
Expires: -1
Cache-Control: private, max-age=0
Content-Type: text/html; charset=ISO-8859-1
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Server: gws
...
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close
....

```

**Comment by e5l** [comment]
Could you recheck the snippet with the`socket.close()`?

**Comment by soywiz** [comment]
`close` is not called directly. I am sending a `Connection: close` to a HTTP server thus is the server the one closing the connection.
I would expect it to not throw/print in this case a close exception since Im reading the remaining bytes from a stram (until the close is reached).

**Comment by e5l** [comment]
Fixed here https://github.com/ktorio/ktor/commit/2645909796913c10d8a9beea58b71eebb30168b8
