### ISSUE TITLE
Uploading file without contenttype and filename cause server error

### ISSUE THREAD

**Issue by kobe2000** [ktorio/ktor#458]
Hi
I use Apache HttpClient library to submit a multipart form to ktor service, 
Using the following Entity:
```
val entity = MultipartEntityBuilder.create()
                .addBinaryBody("image", img)
```
Then there will be exception at server.
```
kotlinx.io.core.MalformedUTF8InputException: Expected 2 more character bytes
	at kotlinx.io.core.ByteReadPacket.readUtf8(Packet.kt:488)
	at kotlinx.io.core.ByteReadPacket.readASCII(Packet.kt:267)
	at kotlinx.io.core.ByteReadPacket.readText(Packet.kt:224)
	at kotlinx.io.core.ByteReadPacket.readText$default(Packet.kt:220)
	at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartData.kt:115)
	at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.doResume(CIOMultipartData.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
If I set contenttype and filename, the exception will dispear.
```
val entity = MultipartEntityBuilder.create()
                .addBinaryBody("image", img, ContentType.create("image/jpeg"), "ximg")
```

**Comment by cy6erGn0m** [comment]
This is because there is no way to detect part kind with no filename. So the server is trying to parse it as a regular form field.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-772">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Answered
