### ISSUE TITLE
Netty timeout

### ISSUE THREAD

**Issue by epool** [ktorio/ktor#460]
I'm have this piece of code 
```kotlin
val ipCheckResult: IpCheckResult = IpApiKlient.getIpInfo(ip).await()
    try {
        val profilePictureUrl = Pikmail.getProfilePictureUrl(email, size?.toInt()).await()
        call.respondRedirect(profilePictureUrl)
...
```

`IpApiKlient` and `Pikmail` are rest clients using retrofit for fetching info from third party REST APIs.

This code is deployed and working on heroku, but sometimes my heroku site stops working and the log error is something like this, I'm not sure what the error could be, if you could point me to the right direction it would be helpful. In advance thanks!

```
2018-07-03T20:15:51.916815+00:00 app[web.1]: Jul 03, 2018 8:15:51 PM okhttp3.internal.platform.Platform log
2018-07-03T20:15:51.916851+00:00 app[web.1]: INFO: <-- HTTP FAILED: java.net.SocketTimeoutException: connect timed out
2018-07-03T20:15:51.917116+00:00 app[web.1]: 20:15:51.916 [nettyCallPool-4-2] ERROR ktor.application - Unhandled: GET - /mitchelliottjr@gmail.com
2018-07-03T20:15:51.917119+00:00 app[web.1]: java.net.SocketTimeoutException: connect timed out
2018-07-03T20:15:51.917121+00:00 app[web.1]: at java.net.PlainSocketImpl.socketConnect(Native Method)
2018-07-03T20:15:51.917123+00:00 app[web.1]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2018-07-03T20:15:51.917125+00:00 app[web.1]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2018-07-03T20:15:51.917127+00:00 app[web.1]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2018-07-03T20:15:51.917128+00:00 app[web.1]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2018-07-03T20:15:51.917130+00:00 app[web.1]: at java.net.Socket.connect(Socket.java:589)
2018-07-03T20:15:51.917132+00:00 app[web.1]: at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
2018-07-03T20:15:51.917134+00:00 app[web.1]: at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
2018-07-03T20:15:51.917135+00:00 app[web.1]: at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
2018-07-03T20:15:51.917137+00:00 app[web.1]: at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
2018-07-03T20:15:51.917139+00:00 app[web.1]: at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2018-07-03T20:15:51.917140+00:00 app[web.1]: at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2018-07-03T20:15:51.917142+00:00 app[web.1]: at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2018-07-03T20:15:51.917143+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2018-07-03T20:15:51.917147+00:00 app[web.1]: at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2018-07-03T20:15:51.917145+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2018-07-03T20:15:51.917148+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2018-07-03T20:15:51.917150+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2018-07-03T20:15:51.917151+00:00 app[web.1]: at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2018-07-03T20:15:51.917153+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2018-07-03T20:15:51.917155+00:00 app[web.1]: at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2018-07-03T20:15:51.917156+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2018-07-03T20:15:51.917158+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2018-07-03T20:15:51.917160+00:00 app[web.1]: at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
2018-07-03T20:15:51.917161+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2018-07-03T20:15:51.917162+00:00 app[web.1]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2018-07-03T20:15:51.917164+00:00 app[web.1]: at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2018-07-03T20:15:51.917166+00:00 app[web.1]: at okhttp3.RealCall.execute(RealCall.java:77)
2018-07-03T20:15:51.917167+00:00 app[web.1]: at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
2018-07-03T20:15:51.917169+00:00 app[web.1]: at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
2018-07-03T20:15:51.917170+00:00 app[web.1]: at io.reactivex.Observable.subscribe(Observable.java:12036)
2018-07-03T20:15:51.917172+00:00 app[web.1]: at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
2018-07-03T20:15:51.917174+00:00 app[web.1]: at io.reactivex.Observable.subscribe(Observable.java:12036)
2018-07-03T20:15:51.917176+00:00 app[web.1]: at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
2018-07-03T20:15:51.917178+00:00 app[web.1]: at io.reactivex.Single.subscribe(Single.java:3313)
2018-07-03T20:15:51.917179+00:00 app[web.1]: at kotlinx.coroutines.experimental.rx2.RxAwaitKt.await(RxAwait.kt:86)
2018-07-03T20:15:51.917181+00:00 app[web.1]: at com.nearsoft.pikmail.api.Main$Companion$main$1$1$2.doResume(Main.kt:46)
2018-07-03T20:15:51.917183+00:00 app[web.1]: at com.nearsoft.pikmail.api.Main$Companion$main$1$1$2.invoke(Main.kt)
2018-07-03T20:15:51.917184+00:00 app[web.1]: at com.nearsoft.pikmail.api.Main$Companion$main$1$1$2.invoke(Main.kt:25)
...
```

**Comment by e5l** [comment]
Hi @epool.
It looks like the issue is in `Pikmail` or on the remote server(with connection `timeout`).
