### ISSUE TITLE
ConcurrentModificationException inside ktor Routing.kt, line 121

### ISSUE THREAD

**Issue by coder82** [ktorio/ktor#468]
Ok so basically today I was looking the logs of one of my servers and I found the exception below from ktor code territory. I don't know exactly what caused it, but essentially my application just uses a websocket to send some text data from the browser forth and back and keeps the connection open as long as the browser window is open, otherwise the connection is closed. I saw this exception only once, then it never happened again, could it be a race condition? Maybe trying to modify a data stricture while you iterate it...
Somebody suggested it might be related to [this issue](https://github.com/ktorio/ktor/issues/462).

```
2018-07-05 17:58:22.516	nettyWorkerPool-3-3 @coroutine#14	Routing.kt	121	doResume	ERROR	Application	Websocket handler failed
java.util.ConcurrentModificationException: null 
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907) 
    at java.util.ArrayList$Itr.remove(ArrayList.java:871) 
    at processes.AdapterController$listen$2$$special$$inlined$forEach$lambda$1.doResume(AdapterController.kt:72) 
    at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42) 
    at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162) 
    at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26) 
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by e5l** [comment]
Could you provide your WebSocket handler?
Look's like you have concurrent access to ArrayList

**Comment by e5l** [comment]
Closed. Please reopen if the problem reproduces.
