### ISSUE TITLE
Exception when instantiating HttpClient in version 0.9.3

### ISSUE THREAD

**Issue by zjuhasz** [ktorio/ktor#502]
Dependencies are all resolving fine, version 0.9.2 is working as expected but it breaks with the only difference being changing the version number to 0.9.3.

This is my man function.
```
import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO

fun main(args: Array<String>) {
    HttpClient(CIO)
}
```

This is the stack trace.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.ktor.client.engine.cio.HttpsConfig.<init>(CIOEngineConfig.kt:26)
	at io.ktor.client.engine.cio.CIOEngineConfig.<init>(CIOEngineConfig.kt:9)
	at io.ktor.client.engine.cio.CIO.create(CIO.kt:14)
	at io.ktor.client.engine.HttpClientEngineFactory$DefaultImpls.create$default(HttpClientEngine.kt:36)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:32)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:31)
	at me.test.MainKt.main(Main.kt:7)
Caused by: java.lang.NumberFormatException: For input string: "172-solus"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.ktor.network.tls.platform.PlatformVersion$Companion.invoke(PlatformVersion.kt:10)
	at io.ktor.network.tls.platform.PlatformVersionKt$platformVersion$2.invoke(PlatformVersion.kt:19)
	at io.ktor.network.tls.platform.PlatformVersionKt$platformVersion$2.invoke(PlatformVersion.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.network.tls.platform.PlatformVersionKt.getPlatformVersion(PlatformVersion.kt)
	at io.ktor.network.tls.CipherSuitesKt.isSupported(CipherSuites.kt:81)
	at io.ktor.network.tls.CIOCipherSuites.<clinit>(CipherSuites.kt:77)
	... 7 more
```

"172-solus" in the stack trace is interesting as I am using Solus Linux.

**Comment by zjuhasz** [comment]
Just tested it on on zulu openjdk 8 binary and that is working fine as well. Starting to suspect this may be a very well hidden bug in the solus jdk and not a bug in this ktor. I'll leave this open though encase someone wants to look into it.

**Comment by soywiz** [comment]
It looks like it is this code:
https://github.com/ktorio/ktor/blob/afa45ccd42011ff5f73e639aca12795cd7f267b0/ktor-network-tls/src/io/ktor/network/tls/platform/PlatformVersion.kt#L7

Looks like in normal circumstances java version (java.version) looks like 1.8.0_130, in your case looks like it is 172-solus or 172-solus_something.

The parsed versions looks like is used here:
https://github.com/ktorio/ktor/blob/afa45ccd42011ff5f73e639aca12795cd7f267b0/ktor-network-tls/src/io/ktor/network/tls/CipherSuites.kt#L80
And probably with another numeric schema it won't work fine.
There it looks like it is just trying to separate the patch version from the main version.

@e5l what do you think?

**Comment by e5l** [comment]
Hi, @zjuhasz. Thanks for the report.
It's obviously a bug with version checking.
We'll fix it soon.

**Comment by e5l** [comment]
fix in `master`
