### ISSUE TITLE
Gracefully handle WebSocket closures

### ISSUE THREAD

**Issue by raharrison** [ktorio/ktor#510]
I'm using the WebSockets feature as a kind of notification/updates mechanism meaning that I'm only really interested in the `outgoing` channel. I'm using the something similar to the following to capture the channel and give it to a service to send updates to etc:

```kotlin
    webSocket("/updates") {
        try {
            myService.add(outgoing) // pass to service for usage
            while(true) 
                  incoming.receive() // throws exception here when closed
        } finally {
             myService.remove(outgoing) // remove when closed via exception
        }
    }
```

This works fine and works correctly, however on closure of the websocket I still get an exception in the logs coming from deep in Netty. This is not ideal for me as my logs are likely to get cluttered when handling a lot of websocket connections.

```
2018-08-05 13:23:42.274 [nettyWorkerPool-3-1] ERROR ktor.application - Websocket handler failed
kotlinx.coroutines.experimental.channels.ClosedReceiveChannelException: Channel was closed
	at kotlinx.coroutines.experimental.channels.Closed.getReceiveException(AbstractChannel.kt:1009)
	at kotlinx.coroutines.experimental.channels.AbstractChannel$ReceiveElement.resumeReceiveClosed(AbstractChannel.kt:852)
	at kotlinx.coroutines.experimental.channels.AbstractSendChannel.close(AbstractChannel.kt:262)
	at kotlinx.coroutines.experimental.channels.SendChannel$DefaultImpls.close$default(Channel.kt:96)
	at io.ktor.http.cio.websocket.DefaultWebSocketSessionImpl$runIncomingProcessor$1.doResume(DefaultWebSocketSessionImpl.kt:102)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.ResumeModeKt.resumeMode(ResumeMode.kt:56)
	at kotlinx.coroutines.experimental.DispatchedKt.dispatch(Dispatched.kt:194)
	at kotlinx.coroutines.experimental.AbstractContinuation.onCompletionInternal(AbstractContinuation.kt:206)
	at kotlinx.coroutines.experimental.AbstractContinuation.completeStateUpdate(AbstractContinuation.kt:341)
	at kotlinx.coroutines.experimental.CancellableContinuationImpl.completeResume(CancellableContinuation.kt:322)
	at kotlinx.coroutines.experimental.channels.AbstractChannel$ReceiveHasNext.completeResumeReceive(AbstractChannel.kt:880)
	at kotlinx.coroutines.experimental.channels.ArrayChannel.offerInternal(ArrayChannel.kt:85)
	at kotlinx.coroutines.experimental.channels.AbstractSendChannel.offer(AbstractChannel.kt:181)
	at kotlinx.coroutines.experimental.channels.AbstractSendChannel.send(AbstractChannel.kt:175)
	at io.ktor.http.cio.websocket.WebSocketReader.handleFrameIfProduced(WebSocketReader.kt:99)
	at io.ktor.http.cio.websocket.WebSocketReader.parseLoop(WebSocketReader.kt:81)
	at io.ktor.http.cio.websocket.WebSocketReader.readLoop(WebSocketReader.kt:63)
	at io.ktor.http.cio.websocket.WebSocketReader$readLoop$1.doResume(WebSocketReader.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-08-05 13:23:42.277 [nettyCallPool-4-1] TRACE ktor.application - 101 Switching Protocols: GET - /updates
```

Is there any way around this or a preferred way of handling purely outgoing websocket connections? Relying on the exception from `incoming.receive` for closure so I can remove the handler doesn't feel right.

**Comment by e5l** [comment]
Could you use?
```
while (true) {
    val message = incoming.receiveOrNull() ?: break
}
```

or
``` 
incoming.consumeEach { message -> 
}

// some final code
```

**Comment by raharrison** [comment]
Both give the same overall behaviour, however `consumeEach` gives this exception instead:

```
Exception in thread "nettyWorkerPool-3-3" java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:236)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:226)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Some interesting behaviour on the first option though:

```kotlin
while(true)
    incoming.receiveOrNull() ?: break
```

Seems very inconsistent. It sometimes gives the same exception as above, on other runs it works without any exceptions being logged. It's definitely better but I can't seem to find any consistent behaviour with it - sometimes it throws an exception, other times everything is good.

**Comment by e5l** [comment]
Could you reproduce the problem with `1.1.1`?
