### ISSUE TITLE
Failed to pass multipart boundary: unexpected end of stream

### ISSUE THREAD

**Issue by kobe2000** [ktorio/ktor#516]
Hi
I use apache httpclient to upload files to server backed by ktor, and often encounter such exceptions:

```
java.io .IOException: Failed to pass multipart boundary: unexpected end of stream
	at io.ktor.http.cio.MultipartKt$boundary$2.doResume(Multipart.kt:94)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlinx.coroutines.experimental.ResumeModeKt.resumeMode(ResumeMode.kt:56)
	at kotlinx.coroutines.experimental.DispatchedKt.dispatch(Dispatched.kt:194)
	at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.resume(MutableDelegateContinuation.kt:89)
	at kotlinx.coroutines.experimental.io 

.ByteBufferChannel.resumeReadOp(ByteBufferChannel.kt:2109)
	at kotlinx.coroutines.experimental.io 

.ByteBufferChannel.flushImpl(ByteBufferChannel.kt:140)
	at kotlinx.coroutines.experimental.io 

.ByteBufferChannel.flush(ByteBufferChannel.kt:146)
	at kotlinx.coroutines.experimental.io 

.ByteBufferChannel.writeAsMuchAsPossible(ByteBufferChannel.kt:2569)
	at kotlinx.coroutines.experimental.io 

.ByteBufferChannel.writeFullySuspend(ByteBufferChannel.kt:1154)
	at kotlinx.coroutines.experimental.io 

.ByteBufferChannel$writeFullySuspend$1.doResume(ByteBufferChannel.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.io 

.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kobe2000** [comment]
Hi, here's the client code. The exception occurs about once a day. I will try to ensure the network is stable.
```
public static void post(String _id, File[] file, CloseableHttpClient httpClient) throws Exception {
        String url = ...;
        ContentType contentType = ContentType.create("text/plain", Charset.forName("utf-8"));
        MultipartEntityBuilder multibuilder = MultipartEntityBuilder.create();
        multibuilder.addTextBody("_id", _id, contentType);
        for (int i = 0; i < 10; i++) {
            if (file[i] != null)
                multibuilder.addBinaryBody("image[" + i + "]", file[i], ContentType.APPLICATION_OCTET_STREAM, "image");
        }
        multibuilder.addTextBody("_dir", "100w", contentType);

        HttpEntity reqEntity = multibuilder.build();
        HttpPost httpPost = new HttpPost(url);
        httpPost.setEntity(reqEntity);
        CloseableHttpResponse response = httpClient.execute(httpPost);
        HttpEntity resultEntity = response.getEntity();
        String responseMessage = "";
        try {
            if (resultEntity != null) {
                InputStream is = resultEntity.getContent();
                BufferedReader br = new BufferedReader(new InputStreamReader(is));
                StringBuffer sb = new StringBuffer();
                String line = "";
                while ((line = br.readLine()) != null) {
                    sb.append(line);
                }
                responseMessage = sb.toString();
//                System.out.println(responseMessage);
            }
            EntityUtils.consume(resultEntity);
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            if (null != response) {
                response.close();
            }
        }
    }
```
The server part is simple, except I write an extension funtion to delete the temporary files
```
private suspend inline fun ApplicationCall.forEachPart(crossinline cb: (PartData) -> Unit) {
    receiveMultipart().forEachPart {
        try {
            cb(it)
        } finally {
            it.dispose()
        }
    }
}
```

**Comment by flyingobjex** [comment]
I'm getting the same error 

`{  "error": "java.io.IOException: Broken delimiter occurred" }`

every time when sending a from w/ file via Postman, with this header:
`
Content-Type: multipart/form-data;boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
`
```
 post(ENDPOINT) {
           if (call.request.isMultipart()) {
                val multipart = call.receiveMultipart()
                print("multipart = " + multipart) <-- it makes it to here, printing io.ktor.http.cio.CIOMultipartDataBase@6cb3aa16multipart...
                multipart.forEachPart { // <--- it breaks here when entering forEachPart loop
                    print("it = " + it)
                }
                val formItems = multipart.readAllParts()
                call.respondText("recvd: $multipart")
            } else {
                call.respond("no multipart, fix request!")
            }
}
```

Was this working in a previous version of Ktor?

**Comment by kobe2000** [comment]
@flyingobjex maybe same as #482 issue?
