### ISSUE TITLE
CIO throws exception if java platform version contains hyphen (e.g. 1.8.0_152-release)

### ISSUE THREAD

**Issue by antanas-arvasevicius** [ktorio/ktor#546]
Hi,
tried to use HttpClient(CIO) but got exception:
```text
Caused by: java.lang.NumberFormatException: For input string: "152-release"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.ktor.network.tls.platform.PlatformVersion$Companion.invoke(PlatformVersion.kt:10)
	at io.ktor.network.tls.platform.PlatformVersionKt$platformVersion$2.invoke(PlatformVersion.kt:19)
	at io.ktor.network.tls.platform.PlatformVersionKt$platformVersion$2.invoke(PlatformVersion.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.network.tls.platform.PlatformVersionKt.getPlatformVersion(PlatformVersion.kt)
	at io.ktor.network.tls.CipherSuitesKt.isSupported(CipherSuites.kt:81)
	at io.ktor.network.tls.CIOCipherSuites.<clinit>(CipherSuites.kt:77)
```
Variables:
`System.getProperty("java.version") -> "1.8.0_152-release"`

Tested on latest ktor 0.9.3 version, os: Mac 10.13.2

https://github.com/ktorio/ktor/blob/cc0dded21f03d5a1e5b36f6f45a8bd42080322a6/ktor-network/ktor-network-tls/src/io/ktor/network/tls/platform/PlatformVersion.kt#L11

**Comment by e5l** [comment]
Ho, @antanas-arvasevicius. Thanks for the report.
Could you test it with `0.9.4-alpha-2`?

**Comment by e5l** [comment]
The problem already fixed in master and the fix would appear in next release.

**Comment by antanas-arvasevicius** [comment]
Thanks :)
