### ISSUE TITLE
Startup exception from GMTDate constructor

### ISSUE THREAD

**Issue by e5l** [ktorio/ktor#552]
Server: Netty
jdk: 10

```
"nettyCallPool-7-2@6334" prio=10 tid=0x3b nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:285)
      at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:262)
      at sun.util.locale.provider.CalendarDataUtility.retrieveFirstDayOfWeek(CalendarDataUtility.java:75)
      at java.util.Calendar.setWeekCountData(Calendar.java:3411)
      at java.util.Calendar.<init>(Calendar.java:1611)
      at java.util.GregorianCalendar.<init>(GregorianCalendar.java:738)
      at java.util.Calendar$Builder.build(Calendar.java:1493)
      at sun.util.locale.provider.CalendarProviderImpl.getInstance(CalendarProviderImpl.java:87)
      at java.util.Calendar.createCalendar(Calendar.java:1696)
      at java.util.Calendar.getInstance(Calendar.java:1675)
      at io.ktor.util.date.DateJvmKt.GMTDate(DateJvm.kt:7)
      at io.ktor.util.date.DateJvmKt.GMTDate$default(Unknown Source:-1)
      at io.ktor.sessions.SessionTransportCookie.send(SessionTransportCookie.kt:25)
      at io.ktor.sessions.Sessions$Feature$install$2.doResume(Sessions.kt:55)
      at io.ktor.sessions.Sessions$Feature$install$2.invoke(Unknown Source:-1)
      at io.ktor.sessions.Sessions$Feature$install$2.invoke(Sessions.kt:21)
      at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
      at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:23)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint.uiConfig(ApplicationResponseFunctions.kt:23)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint$1$3$1.doResume(UserAuthnEndpoint.kt:57)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint$1$3$1.invoke(Unknown Source:-1)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint$1$3$1.invoke(UserAuthnEndpoint.kt:37)
      at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
      at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:23)
      at io.ktor.routing.Routing.executeResult(Pipeline.kt:202)
      at io.ktor.routing.Routing.interceptor(Routing.kt:25)
      at io.ktor.routing.Routing$Feature$install$1.doResume(Routing.kt:66)
      at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:-1)
      at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:51)
      at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
      at io.ktor.util.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:-1)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
      at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
      at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
      at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:-1)
      at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
      at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.lang.Thread.run(Thread.java:844)
"nettyCallPool-7-2@6334" prio=10 tid=0x3b nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:285)
      at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:262)
      at sun.util.locale.provider.CalendarDataUtility.retrieveMinimalDaysInFirstWeek(CalendarDataUtility.java:84)
      at java.util.Calendar.setWeekCountData(Calendar.java:3412)
      at java.util.Calendar.<init>(Calendar.java:1611)
      at java.util.GregorianCalendar.<init>(GregorianCalendar.java:738)
      at java.util.Calendar$Builder.build(Calendar.java:1493)
      at sun.util.locale.provider.CalendarProviderImpl.getInstance(CalendarProviderImpl.java:87)
      at java.util.Calendar.createCalendar(Calendar.java:1696)
      at java.util.Calendar.getInstance(Calendar.java:1675)
      at io.ktor.util.date.DateJvmKt.GMTDate(DateJvm.kt:7)
      at io.ktor.util.date.DateJvmKt.GMTDate$default(Unknown Source:-1)
      at io.ktor.sessions.SessionTransportCookie.send(SessionTransportCookie.kt:25)
      at io.ktor.sessions.Sessions$Feature$install$2.doResume(Sessions.kt:55)
      at io.ktor.sessions.Sessions$Feature$install$2.invoke(Unknown Source:-1)
      at io.ktor.sessions.Sessions$Feature$install$2.invoke(Sessions.kt:21)
      at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
      at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:23)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint.uiConfig(ApplicationResponseFunctions.kt:23)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint$1$3$1.doResume(UserAuthnEndpoint.kt:57)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint$1$3$1.invoke(Unknown Source:-1)
      at com.molecularinstruments.api.endpoint.UserAuthnEndpoint$1$3$1.invoke(UserAuthnEndpoint.kt:37)
      at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
      at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:23)
      at io.ktor.routing.Routing.executeResult(Pipeline.kt:202)
      at io.ktor.routing.Routing.interceptor(Routing.kt:25)
      at io.ktor.routing.Routing$Feature$install$1.doResume(Routing.kt:66)
      at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:-1)
      at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt:51)
      at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
      at io.ktor.util.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:-1)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
      at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
      at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
      at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
      at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:-1)
      at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
      at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.lang.Thread.run(Thread.java:844)
```

**Comment by cy6erGn0m** [comment]
Notice that these stacktraces are not exceptions but a part of a thread dump
