### ISSUE TITLE
ClosedWriteChannelException: The channel was closed

### ISSUE THREAD

**Issue by NikkyAI** [ktorio/ktor#586]
using ktor 0.9.4
and kotlinx.coroutines 0.26.0

when using a JSON/Rest api with ktor client using CIO engine

```
Exception in thread "io-thread-2 @coroutine#3412" kotlinx.coroutines.experimental.io.ClosedWriteChannelException: The channel was closed
	at kotlinx.coroutines.experimental.io.ByteBufferChannel$ClosedElement.getSendException(ByteBufferChannel.kt:2462)
	at kotlinx.coroutines.experimental.io.ByteBufferChannel.setupStateForWrite(ByteBufferChannel.kt:175)
	at kotlinx.coroutines.experimental.io.ByteBufferChannel.writeByte(ByteBufferChannel.kt:890)
	at io.ktor.network.tls.RenderKt.writeRecord(Render.kt:12)
	at io.ktor.network.tls.TLSClientHandshake$output$1.doResume(TLSClientHandshake.kt:127)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
	at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:73)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:140)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:70)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:46)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
	at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:68)
```

**Comment by e5l** [comment]
Hi, @NikkyAI. Thanks for the request. 
Could you provide the reproducer?

**Comment by e5l** [comment]
Could you report the jdk version and build number(like jdk 1.8_161, or openjdk 1.8-... )?

**Comment by NikkyAI** [comment]
current jdk bundled with idea i think , or openjdk-8 on my system
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
