### ISSUE TITLE
The decoder gets stuck in infinite loop

### ISSUE THREAD

**Issue by Tea-Ayataka** [ktorio/ktor#627]
I don't know the condition though.

Stacktrace:
```"ForkJoinPool.commonPool-worker-3"` #54 daemon prio=5 os_prio=0 tid=0x00007f8c94004000 nid=0x415a runnable [0x00007f8cd83f9000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.cs.UTF_8$Decoder.decodeLoop(UTF_8.java:412)
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:579)
        at kotlinx.io.charsets.CharsetJVMKt.decode(CharsetJVM.kt:163)
        at kotlinx.io.charsets.EncodingKt.decode(Encoding.kt:104)
        at kotlinx.io.core.StringsKt.readText(Strings.kt:324)
        at kotlinx.io.core.StringsKt.readText$default(Strings.kt:323)
        at io.ktor.client.response.HttpResponseKt.readText(HttpResponse.kt:66)
        at io.ktor.client.response.HttpResponseKt$readText$1.doResume(HttpResponse.kt)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
        at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```

Kotlin: 1.2.70
Ktor: 0.9.5

**Comment by cy6erGn0m** [comment]
Already fixed in kotlinx-io Kotlin/kotlinx-io@5905faecb86730b5aeead41e0e9beadebe7ba533  (merged into eap13 branch)
