### ISSUE TITLE
Certs check fail Raw SSL Connection

### ISSUE THREAD

**Issue by OtakuSenpai** [ktorio/ktor#641]
Here is the code:
Possible alternatives to port 6697 are 7000 and 7070.

```
fun main(args: Array<String>) = runBlocking {
    lateinit var output : ByteWriteChannel
    lateinit var input: ByteReadChannel
    var socket = aSocket(ActorSelectorManager(ioCoroutineDispatcher)).tcp()
            .connect(InetSocketAddress("chat.freenode.net",6697)).tls()
    input = socket.openReadChannel()
    output = socket.openWriteChannel(autoFlush = true)
    socket.close()
}
```
Here is the error:
```
Exception in thread "main" java.lang.IllegalStateException: Check failed.
	at io.ktor.network.tls.TLSClientHandshake.handleCertificatesAndKeys(TLSClientHandshake.kt:244)
	at io.ktor.network.tls.TLSClientHandshake$handleCertificatesAndKeys$1.doResume(TLSClientHandshake.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:140)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:70)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:46)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Unknown Source)
	at com.github.otakusenpai.testbot.MainKt.main(main.kt:126)
```

**Comment by cy6erGn0m** [comment]
According to RFC sec. 4.3.2

>  A server which is authenticating with a certificate MAY optionally
   request a certificate from the client.  

However we don't support client certificates for now and it should crash with `Client certificates unsupported` exception that is not thrown unfortunately since we are failing too early with the assertion.
