### ISSUE TITLE
can't create CIO client on android

### ISSUE THREAD

**Issue by 2f554e5562** [ktorio/ktor#698]
lib versions: 
   kotlin_version = '1.3.0'
   anko_version='0.10.7-rc13'
   ktor_version = '1.0.0-beta-3'
```
val client = HttpClient(CIO).config {
    install(WebSockets)
}
```
```
E/MultiWindowProxy: getServiceInstance failed!
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vastaus42.scaner, PID: 11383
    java.lang.NoSuchMethodError: No static method getInstanceStrong()Ljava/security/SecureRandom; in class Ljava/security/SecureRandom; or its super classes (declaration of 'java.security.SecureRandom' appears in /system/framework/core-libart.jar)
        at io.ktor.client.engine.cio.CIOEngineConfigKt.<clinit>(CIOEngineConfig.kt:9)
        at io.ktor.client.engine.cio.CIOEngineConfigKt.access$getDEFAULT_RANDOM$p(CIOEngineConfig.kt:1)
        at io.ktor.client.engine.cio.HttpsConfig.<init>(CIOEngineConfig.kt:29)
        at io.ktor.client.engine.cio.CIOEngineConfig.<init>(CIOEngineConfig.kt:13)
        at io.ktor.client.engine.cio.CIO.create(CIO.kt:14)
        at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:27)
        at io.ktor.client.HttpClientKt.HttpClient$default(HttpClient.kt:24)
        at com.vastaus42.scaner.LoginActivity.onCreate(LoginActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:6405)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2712)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2847)
        at android.app.ActivityThread.access$900(ActivityThread.java:193)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
I/Process: Sending signal. PID: 11383 SIG: 9
Application terminated.
```

**Comment by 2f554e5562** [comment]
@e5l 6.0 (Flyme 7.8.8.31g beta, if it important)

**Comment by emirhanemmez** [comment]
`@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {
    @Provides
    @Singleton
    fun createKtorClient(): HttpClient =
        HttpClient(CIO).config {
            defaultRequest {
                url("http://localhost:8080")
                contentType(ContentType.Application.Json)
                accept(ContentType.Application.Json)
            }
            install(Logging) {
                level = LogLevel.ALL
            }
            install(ContentNegotiation) {
                json()
            }
        }
}`

When I want to create a client with Hilt. I'm getting this error:
java.lang.NoSuchMethodError: No virtual method getModule()Ljava/lang/Module; in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /apex/com.android.art/javalib/core-oj.jar)

JDK 11 
Ktor version 2.2.2
Hilt version 2.44
Gradle version 7.4.2
Kotlin version 1.8.10
