### ISSUE TITLE
https issue with CIO engine in ktor-client

### ISSUE THREAD

**Issue by ruXlab** [ktorio/ktor#703]
I found that concurrent request using CIO engine fail after some time. This issue affects https websites only, for plain http CIO works perfect. If engine is changed to to `Apache` or `OkHttp` everything works well

Sample code:

```kotlin
fun main() {
    val client = HttpClient(CIO) {
        followRedirects = false
        engine {
            maxConnectionsCount = 1000000
            endpoint.connectRetryAttempts = 1
            endpoint.maxConnectionsPerRoute = 10000
        }
    }

    fun CoroutineScope.getter(workerNumber: Int, url: String) = launch {
        var counter = 0
        while(isActive) {
            val time = measureTimeMillis {
                client.get(url)
            }
            println("$url worker#$workerNumber finished, time used: ${time}ms, req#${counter++}")
        }
    }

    runBlocking {
        for(i in 0..10) {
            getter(i, "http://blank.org")
            getter(i, "https://www.facebook.com")
        }
    }
}
```

Sample output if fetching https only:
```
https://www.facebook.com worker#0 finished, time used: 1038ms, req#0
https://www.facebook.com worker#4 finished, time used: 995ms, req#0
https://www.facebook.com worker#1 finished, time used: 995ms, req#0
https://www.facebook.com worker#7 finished, time used: 1014ms, req#0
https://www.facebook.com worker#4 finished, time used: 188ms, req#1

<STUCK>
```

And for plain http:

```
http://blank.org worker#0 finished, time used: 640ms, req#0
http://blank.org worker#1 finished, time used: 565ms, req#0
http://blank.org worker#2 finished, time used: 665ms, req#0
. . . . . . . 
http://blank.org worker#7 finished, time used: 121ms, req#75
http://blank.org worker#8 finished, time used: 121ms, req#76
http://blank.org worker#10 finished, time used: 119ms, req#76
http://blank.org worker#3 finished, time used: 122ms, req#77
http://blank.org worker#4 finished, time used: 117ms, req#76
. . . . . . .
```

This issue doesn't seem to be facebook specific - it happens on all https websites I have tried

------------------
Environment:
Ubuntu 16.04
Oracle Java 1.8.0_191
Kotlin: 1.3.0
Ktor client: 1.0.0-beta-3

**Comment by serebit** [comment]
Possibly same thing happening to me using CIO. After some time, I get this:
```
Exception in thread "DefaultDispatcher-worker-1" kotlinx.coroutines.channels.ClosedReceiveChannelException: Channel was closed
	at kotlinx.coroutines.channels.Closed.getReceiveException(AbstractChannel.kt:1070)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.resumeReceiveClosed(AbstractChannel.kt:914)
	at kotlinx.coroutines.channels.AbstractSendChannel.helpClose(AbstractChannel.kt:320)
	at kotlinx.coroutines.channels.AbstractSendChannel.close(AbstractChannel.kt:256)
	at kotlinx.coroutines.channels.ChannelCoroutine.close(ChannelCoroutine.kt)
	at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:94)
	at io.ktor.network.tls.TLSClientHandshake$input$1.invokeSuspend(TLSClientHandshake.kt:98)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```
Only seems to happen when sending packets to https, and not http, with discord's API endpoints. My environment is as follows:
Solus 3.9999
OpenJDK 1.8.0_172
Kotlin 1.3.0
Ktor client 1.0.0-rc
