### ISSUE TITLE
ktor-client with okhttp engine is leaking connection

### ISSUE THREAD

**Issue by ruXlab** [ktorio/ktor#710]
I stumbled upon this flaky problem while using `okhttp` engine. From my observation it appears faster with increased concurrency level.

Sample code:
```kotlin
fun main() {
    Logger.getLogger(OkHttpClient::class.java.name).level = Level.FINE

    val client = HttpClient(OkHttp) {
        followRedirects = false
    }

    runBlocking {
        for(c in 0..10) launch {
            for (i in 0..10000) {
                val time = measureTimeMillis {
                    client.get("https://www.google.co.uk/")
                }
                println("coroutine#$c req#$i finished, time used: ${time}ms")
            }
        }
    }
```

And it's output:

```
coroutine#4 req#0 finished, time used: 711ms
coroutine#1 req#0 finished, time used: 727ms
coroutine#2 req#0 finished, time used: 725ms
. . . . 
coroutine#0 req#8 finished, time used: 423ms
coroutine#5 req#8 finished, time used: 415ms
coroutine#7 req#8 finished, time used: 501ms
Nov 08, 2018 4:31:18 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://www.google.co.uk/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
	at okhttp3.RealCall.enqueue(RealCall.java:98)
	at io.ktor.client.engine.okhttp.OkUtilsKt.execute(OkUtils.kt:11)
	at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:35)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invokeSuspend(HttpClient.kt:74)
	at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invoke(HttpClient.kt)
	at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:53)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
	at io.ktor.client.features.HttpSend$DefaultSender.execute(HttpSend.kt:86)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:58)
	at io.ktor.client.features.HttpSend$Feature$install$1.invoke(HttpSend.kt)
	at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:53)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
	at io.ktor.client.HttpClient.execute(HttpClient.kt:139)
	at io.ktor.client.call.HttpClientCallKt.call(HttpClientCall.kt:79)
	at io.ktor.client.call.UtilsKt.call(utils.kt:16)
	at ktorclienttest.HttpRequester2Kt$main$1$1.invokeSuspend(HttpRequester2.kt:71)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
	at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ktorclienttest.HttpRequester2Kt.main(HttpRequester2.kt:24)
	at ktorclienttest.HttpRequester2Kt.main(HttpRequester2.kt)

< ^^^^^ repeated 88 times >

. . . . . 
coroutine#6 req#8 finished, time used: 558ms
coroutine#9 req#8 finished, time used: 675ms
coroutine#3 req#9 finished, time used: 606ms
. . . . 
```

Also I noticed that with low round robin time(<100ms) this issue almost never appears.

Looking on [OkUtils](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-okhttp/src/io/ktor/client/engine/okhttp/OkUtils.kt#L8) and how it works [with stream](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-okhttp/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt#L39) I recreated a similar flow but without using coroutines, which seem to be working as expected

```kotlin
fun main() {
    val client = OkHttpClient.Builder().build()
    for(i in 0..10000) {
        val r = okhttp3.Request.Builder().url("https://www.google.co.uk/").build()
        client.newCall(r).enqueue(object : Callback {
            override fun onFailure(call: Call, cause: IOException) {
                println("req#$i failed with ${cause}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.body()?.use { it.byteStream().reader().readText() }
                println("req#$i ok")
            }
        })
    }
}
```

No warnings about leaked connection were popped out

-------------

Environment:
Ubuntu 16.04
Oracle Java 1.8.0_191
Kotlin 1.3.0
Ktor client 1.0.0-beta-3
OkHttp 3.11.0

**Comment by iNoles** [comment]
ResponseBody have to be close in all conditions. String one is always close the body.

**Comment by ruXlab** [comment]
@iNoles that's correct

Shouldn't `client.get("https://www.google.co.uk/")` do that?

[Seems like](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-okhttp/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt#L39) body is always read, isn't it?

**Comment by e5l** [comment]
Hi, @ruXlab. Thanks for the report. It's obviously a bug.
The problem occurs only when you ignore the response body: here the get implicit infer `Unit` type.

Current workaround: specify the content type explicitly.
`client.get<String>("...")`
