### ISSUE TITLE
ktor-client-cio NetworkOnMainThread exception when launched on Dispatchers.Main

### ISSUE THREAD

**Issue by gabin8** [ktorio/ktor#764]
### Ktor Version
1.0.0
### Ktor Engine Used(client or server and name)
ktor-client-cio
### JVM Version, Operating System and Relevant Context
Android 8.0 Oreo
### Feedback

When CIO client makes request on main dispatcher, it gets a crash android.os.NetworkOnMainThreadException

>2018-11-28 15:27:04.155 17482-17482/com.example.android.kotlincoroutines E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.kotlincoroutines, PID: 17482
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1448)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
        at java.net.InetAddress.getByName(InetAddress.java:743)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:231)
        at io.ktor.client.engine.cio.Endpoint.<init>(Endpoint.kt:36)
        at io.ktor.client.engine.cio.CIOEngine$executeRequest$$inlined$with$lambda$1.apply(CIOEngine.kt:36)
        at io.ktor.client.engine.cio.CIOEngine$executeRequest$$inlined$with$lambda$1.apply(CIOEngine.kt:13)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1715)
        at io.ktor.client.engine.cio.CIOEngine.executeRequest(CIOEngine.kt:34)
        at io.ktor.client.engine.cio.CIOEngine.execute(CIOEngine.kt:23)
        at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invokeSuspend(HttpClient.kt:74)
        at io.ktor.client.HttpClient$$special$$inlined$apply$lambda$1.invoke(Unknown Source:12)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:63)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:111)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:131)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
        at io.ktor.client.features.HttpSend$DefaultSender.execute(HttpSend.kt:86)
        at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:58)
        at io.ktor.client.features.HttpSend$Feature$install$1.invoke(Unknown Source:12)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:63)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:111)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:131)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
        at io.ktor.client.HttpClient.execute(HttpClient.kt:139)
        at io.ktor.client.call.HttpClientCallKt.call(HttpClientCall.kt:78)
        at io.ktor.client.call.UtilsKt.call(utils.kt:16)
        at com.example.android.kotlincoroutines.main.MainViewModel.testSusp(MainViewModel.kt:131)
        at com.example.android.kotlincoroutines.main.MainViewModel$doSomeNetworkCall$1.invokeSuspend(MainViewModel.kt:92)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at android.os.Handler.handleCallback(Handler.java:792)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

Snippet:
>val scope = CoroutineScope(Dispatchers.Main)
        scope.launch {
            val client = HttpClient(CIO)
            val response = client.get<String>("https://httpstat.us/200")    // get a crash here
            println("Response: $response")
        }

**ktor-client-android** and **ktor-client-okhttp** doesn't lead to crash with same code

**Comment by luca992** [comment]
As the error describes, you shouldn't be doing network calls in the main thread... Also, android doesn't allow it.

**Comment by gabin8** [comment]
> As the error describes, you shouldn't be doing network calls in the main thread... Also, android doesn't allow it.

As I've said, the behavior should be consistent for all ktor http clients. If you have client independent code you shouldn't make any changes just for a separate one. The code works well for ktor-client-android and ktor-client-okhttp and doesn't lead to crash

**Comment by iNoles** [comment]
Dispatchers.Main is Main Thread Only.

**Comment by gabin8** [comment]
Still happens on 1.0.1
