### ISSUE TITLE
IllegalArgumentException: Neither port nor sslPort specified.

### ISSUE THREAD

**Issue by GurpreetSK95** [ktorio/ktor#775]
For Ktor 1.0.0 server, java version 1.8.0_181 (running server on localhost, Ubuntu 18.04.1 LTS)

Facing the following issue:
```
Exception in thread "main" java.lang.IllegalArgumentException: Neither port nor sslPort specified. Use command line options -port/-sslPort or configure connectors in application.conf
	at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt:121)
	at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt)
	at io.ktor.server.engine.ApplicationEngineEnvironmentBuilder.build(ApplicationEngineEnvironment.kt:95)
	at io.ktor.server.engine.ApplicationEngineEnvironmentKt.applicationEngineEnvironment(ApplicationEngineEnvironment.kt:40)
	at io.ktor.server.engine.CommandLineKt.commandLineEnvironment(CommandLine.kt:50)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:16)
	at com.gurpreetsk.ApplicationKt.main(Application.kt:36)
```

However, the `application.conf` file contains the following:
```
ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.gurpreetsk.ApplicationKt.module ]
  }
}
```

**Comment by cy6erGn0m** [comment]
Most likely `application.conf` is not in the classpath

**Comment by GurpreetSK95** [comment]
How do I add it to the classpath? It is not working of a new ktor project either.

**Comment by cy6erGn0m** [comment]
Is it placed in a resources source root?

**Comment by GurpreetSK95** [comment]
Yes. Attaching project structure screenshot along-with:
![screenshot from 2018-12-06 11-01-29](https://user-images.githubusercontent.com/11317262/49563576-72920800-f946-11e8-9c91-47ee7b00bfa2.png)

**Comment by cy6erGn0m** [comment]
That's quite strange that you have orange test and out directories. For sure something is configured. 

`application.conf` should be in `out` directory, like this:

![screenshot_20181207_151208](https://user-images.githubusercontent.com/762598/49647133-8c107e00-fa32-11e8-8ad3-8eba3285ace6.png)

I've just tried to create a project using [ktor plugin](https://plugins.jetbrains.com/plugin/10823-ktor) and it runs just fine in IDEA and via gradle as well. Same for website https://start.ktor.io

**Comment by GurpreetSK95** [comment]
Let me try and update here in some time if I solve this.

**Comment by GurpreetSK95** [comment]
No. I still can't figure out what's wrong. However, it seems like a machine issue (wrong PATH or something) as the project runs fine on my other machine.

**Comment by AlexTver** [comment]
Hello.
I just update IDEA and ktor plugin and get same issue.
It's my old good working small feature testing project

ktor 1.0.0, Win7 64

**Comment by yanghengyh** [comment]
I also encountered the same problem. totally do not understand.

**Comment by piritus** [comment]
There was the same problem after the update of the IDE, it helped "Sync Project with Gradle Files"

**Comment by poloynikov** [comment]
i delete ''out'' folder and rebuild... and it is all ok
