### ISSUE TITLE
SSE request hangs if use Compression

### ISSUE THREAD

**Issue by Ccixyj** [ktorio/ktor#817]
### Ktor Version
1.0.1

### Ktor Engine Used(client or server and name)
server netty

### JVM Version, Operating System and Relevant Context
jdk1.8.0_181

### Feedback

base on demo:  ktor-samples/other/sse 

 add code 
```
 install(io.ktor.features.Compression)
```
cause error 
```
kotlinx.coroutines.io.ClosedWriteChannelException: The channel was closed
	at kotlinx.coroutines.io.ByteBufferChannel$ClosedElement.getSendException(ByteBufferChannel.kt:2473)
	at kotlinx.coroutines.io.ByteBufferChannel.setupStateForWrite(ByteBufferChannel.kt:179)
	at kotlinx.coroutines.io.ByteBufferChannel.access$setupStateForWrite(ByteBufferChannel.kt:21)
	at kotlinx.coroutines.io.ByteBufferChannel.writeAsMuchAsPossible(ByteBufferChannel.kt:2721)
	at kotlinx.coroutines.io.ByteBufferChannel.writeFully(ByteBufferChannel.kt:1441)
	at kotlinx.coroutines.io.jvm.javaio.OutputAdapter$loop$1.loop(Blocking.kt:81)
	at kotlinx.coroutines.io.jvm.javaio.OutputAdapter$loop$1$loop$1.invokeSuspend(Blocking.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at kotlinx.coroutines.io.jvm.javaio.UnsafeBlockingTrampoline.dispatch(Blocking.kt:263)
	at kotlinx.coroutines.DispatchedContinuation.resumeWith(Dispatched.kt:107)
	at kotlinx.coroutines.io.jvm.javaio.BlockingAdapter.submitAndAwait(Blocking.kt:212)
	at kotlinx.coroutines.io.jvm.javaio.BlockingAdapter.submitAndAwait(Blocking.kt:185)
	at kotlinx.coroutines.io.jvm.javaio.OutputAdapter.write(Blocking.kt:107)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at io.ktor.samples.sse.SSeKt$respondSse$2.invokeSuspend(SSe.kt:145)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)

```

so the only solution is add condition for Compression feature?

**Comment by cy6erGn0m** [comment]
For sure compression is not recommended for event streams as far as it does buffered block compression that will lead to delays and timeouts. So event-stream need to be excluded

**Comment by proton72** [comment]
May be you could turn off the compression by default for event streams content type?
