### ISSUE TITLE
TLS Raw Sockets: Expected TLS handshake ServerHello but got ClientHello

### ISSUE THREAD

**Issue by rnett** [ktorio/ktor#886]
### Ktor Version

1.1.1

### Ktor Engine Used(client or server and name)

N/A - Raw Sockets

### JVM Version, Operating System and Relevant Context

1.8.0_172, Windows.

I'm trying to create a basic client/server socket connection.  It works fine without TLS.

When I enable TLS using `.tls(Dispatchers.IO, randomAlgorithm = SecureRandom().algorithm)` (on client and server) I get the exception `Expecting ServerHello but got ClientHello` (on both client and server).  I'm using `SecureRandom().algorithm` so that it works on windows (I want it to be cross platform but haven't looked into it yet).  It evaluates to `SHA1PRNG`.

```kotlin
Exception in thread "main" java.lang.IllegalStateException: Expected TLS handshake ServerHello but got ClientHello
	at io.ktor.network.tls.TLSClientHandshake.receiveServerHello(TLSClientHandshake.kt:204)
	at io.ktor.network.tls.TLSClientHandshake.negotiate(TLSClientHandshake.kt:164)
	at io.ktor.network.tls.TLSClientSession.start(TLSClientSession.kt:32)
	at io.ktor.network.tls.TLSKt.tls(TLS.kt:24)
	at io.ktor.network.tls.TLSKt.tls$default(TLS.kt:16)
	at com.rnett.submit.client.ClientKt$sendFiles$1.invokeSuspend(Client.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.rnett.submit.client.ClientKt.sendFiles(Client.kt:38)
	at com.rnett.submit.client.ClientKt.sendFiles$default(Client.kt:38)
	at com.rnett.submit.client.Client.main(Client.kt:30)
```

On the client and:

```kotlin
Exception in thread "main" java.lang.IllegalStateException: Expected TLS handshake ServerHello but got ClientHello
	at io.ktor.network.tls.TLSClientHandshake.receiveServerHello(TLSClientHandshake.kt:204)
	at io.ktor.network.tls.TLSClientHandshake$receiveServerHello$1.invokeSuspend(TLSClientHandshake.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

on the server.

I think it might be related to (and possibly fixed by) #394, but that is just a wild guess.

**Comment by e5l** [comment]
Hi @rnett, thanks for the report.
`tls` is supported on the client side only for now

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-694">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
