### ISSUE TITLE
Continuous build failure

### ISSUE THREAD

**Issue by rjaros** [ktorio/ktor#912]
### Ktor Version

1.1.2

### Ktor Engine Used(client or server and name)

Netty server

### JVM Version, Operating System and Relevant Context

Java 1.8, Linux

### Feedback

When running gradle continuous build with "-t" option, gradle process fails with NullPointerException after any source code change. The problem is reproducible with official ktor samples.

[rjaros@rjaros1 ktor-samples]$ ./gradlew :chat:build -t --stacktrace
Continuous build is an incubating feature.

> Configure project :fullstack-mpp
Kotlin Multiplatform Projects are an experimental feature.

> Task :chat:compileKotlin
w: /home/rjaros/git/github/ktor-samples/app/chat/src/ChatApplication.kt: (67, 47): This declaration is experimental and its usage should be marked with '@io.ktor.util.KtorExperimentalAPI' or '@UseExperimental(io.ktor.util.KtorExperimentalAPI::class)'
w: /home/rjaros/git/github/ktor-samples/app/chat/src/ChatApplication.kt: (98, 30): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@UseExperimental(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'

BUILD SUCCESSFUL in 3s
9 actionable tasks: 9 executed

Waiting for changes to input files of tasks... (ctrl-d to exit)

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NullPointerException
        at org.gradle.profile.ProfileEventAdapter.beforeResolve(ProfileEventAdapter.java:116)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:370)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:352)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:340)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:327)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy30.beforeResolve(Unknown Source)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.performPreResolveActions(DefaultConfiguration.java:582)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$500(DefaultConfiguration.java:123)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$5.run(DefaultConfiguration.java:531)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:524)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:509)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1800(DefaultConfiguration.java:123)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1037)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1025)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:444)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.jetbrains.kotlin.gradle.scripting.internal.ScriptingGradleSubplugin$configureScriptsExtensions$$inlined$let$lambda$1.invoke(ScriptingGradleSubplugin.kt:97)
        at org.jetbrains.kotlin.gradle.scripting.internal.ScriptingGradleSubplugin$configureScriptsExtensions$$inlined$let$lambda$1.invoke(ScriptingGradleSubplugin.kt:29)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.gradle.scripting.internal.ScriptingGradleSubplugin$configureScriptsExtensions$1$1.isSatisfiedBy(ScriptingGradleSubplugin.kt:105)
        at org.jetbrains.kotlin.gradle.scripting.internal.ScriptingGradleSubplugin$configureScriptsExtensions$1$1.isSatisfiedBy(ScriptingGradleSubplugin.kt:29)
        at org.gradle.api.specs.OrSpec.isSatisfiedBy(OrSpec.java:47)
        at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:47)
        at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:47)
        at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:47)
        at org.gradle.api.internal.file.collections.DirectoryTrees.contains(DirectoryTrees.java:37)
        at org.gradle.api.internal.file.FileSystemSubset.contains(FileSystemSubset.java:85)
        at org.gradle.internal.filewatch.jdk7.WatchPointsRegistry$CombinedRootSubset.contains(WatchPointsRegistry.java:190)
        at org.gradle.internal.filewatch.jdk7.WatchPointsRegistry.shouldFire(WatchPointsRegistry.java:51)
        at org.gradle.internal.filewatch.jdk7.WatchServiceRegistrar.maybeFire(WatchServiceRegistrar.java:237)
        at org.gradle.internal.filewatch.jdk7.WatchServiceRegistrar.onChange(WatchServiceRegistrar.java:206)
        at org.gradle.internal.filewatch.jdk7.WatchServiceFileWatcherBacking.deliverEvents(WatchServiceFileWatcherBacking.java:150)
        at org.gradle.internal.filewatch.jdk7.WatchServiceFileWatcherBacking.pumpEvents(WatchServiceFileWatcherBacking.java:132)
        at org.gradle.internal.filewatch.jdk7.WatchServiceFileWatcherBacking.access$500(WatchServiceFileWatcherBacking.java:41)
        at org.gradle.internal.filewatch.jdk7.WatchServiceFileWatcherBacking$2.run(WatchServiceFileWatcherBacking.java:93)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

**Comment by rjaros** [comment]
I'm sorry for the confusion. It turns out to have nothing to do with Ktor. The problem was the "safe write" option of IntelliJ Idea.
