### ISSUE TITLE
Content of html tag in call.respondHtml needs to be last or causes an IllegalStateException

### ISSUE THREAD

**Issue by wilyarti** [ktorio/ktor#914]
### Ktor Version
ktor_version=1.1.1
kotlin.code.style=official
kotlin_version=1.3.11
logback_version=1.2.1

### Ktor Engine Used(client or server and name)
netty
### JVM Version, Operating System and Relevant Context
Ubuntu 18.04 on amd64
### Feedback
If the +"" attribute is not put last it causes an error.

For example:
```
get("/getPosts2") {
        call.respondHtml {
            body {
                a("#", null) {
                    classes = setOf("navbar-brand", "dropdown-toggle", "bg-dark")
                    attributes["data-toggle"] = "dropdown"
                    attributes["id"] = "dropdownMenuLink"
                    +"""OpenS3"""
                    attributes["aria-expanded"] = "false"
                    attributes["aria-haspopup"] = "true"
                    role = "button"
                }
            }
        }
    }
```
Causes the following error: 

> 2019-02-01 05:55:30.985 [nettyCallPool-4-1] ERROR Application - 200 OK: GET - /getPosts2
java.lang.IllegalStateException: You can't change tag attribute because it was already passed to the downstream
	at kotlinx.html.consumers.DelayedConsumer.onTagAttributeChange(delayed-consumer.kt:19)
	at kotlinx.html.impl.DelegatingMap.put(delegating-map.kt:24)
	at kotlinx.html.impl.DelegatingMap.put(delegating-map.kt:6)
	at net.opens3.apps.ApplicationKt$module$3$1$1$1$1.invoke(Application.kt:51)
	at net.opens3.apps.ApplicationKt$module$3$1$1$1$1.invoke(Application.kt)
	at kotlinx.html.ApiKt.visit(api.kt:80)
	at kotlinx.html.Gen_tag_unionsKt.a(gen-tag-unions.kt:380)
	at kotlinx.html.Gen_tag_unionsKt.a$default(gen-tag-unions.kt:380)
	at net.opens3.apps.ApplicationKt$module$3$1$1$1.invoke(Application.kt:46)
	at net.opens3.apps.ApplicationKt$module$3$1$1$1.invoke(Application.kt)
	at kotlinx.html.ApiKt.visit(api.kt:80)
	at kotlinx.html.Gen_tags_hKt.body(gen-tags-h.kt:164)
	at kotlinx.html.Gen_tags_hKt.body$default(gen-tags-h.kt:164)
	at net.opens3.apps.ApplicationKt$module$3$1$1.invoke(Application.kt:45)
	at net.opens3.apps.ApplicationKt$module$3$1$1.invoke(Application.kt)
	at kotlinx.html.ApiKt.visit(api.kt:80)
	at kotlinx.html.ApiKt.visitAndFinalize(api.kt:93)
	at kotlinx.html.Gen_consumer_tagsKt.html(gen-consumer-tags.kt:317)
	at kotlinx.html.Gen_consumer_tagsKt.html$default(gen-consumer-tags.kt:317)
	at io.ktor.html.HtmlContent.writeTo(RespondHtml.kt:32)
	at io.ktor.features.Compression$CompressedWriteResponse$writeTo$2.invokeSuspend(Compression.kt:151)
	at io.ktor.features.Compression$CompressedWriteResponse$writeTo$2.invoke(Compression.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:186)
	at io.ktor.features.Compression$CompressedWriteResponse.writeTo(Compression.kt:149)
	at io.ktor.server.engine.BaseApplicationResponse$respondWriteChannelContent$$inlined$use$lambda$1.invokeSuspend(BaseApplicationResponse.kt:150)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

Rearranging the code stops the error:
```
get("/getPosts2") {
            call.respondHtml {
                body {
                    a("#", null) {
                        classes = setOf("navbar-brand", "dropdown-toggle", "bg-dark")
                        attributes["data-toggle"] = "dropdown"
                        attributes["id"] = "dropdownMenuLink"
                        attributes["aria-expanded"] = "false"
                        attributes["aria-haspopup"] = "true"
                        role = "button"
                        +"""OpenS3"""

                    }
                }
            }
        }
```

It's not really a big deal. But thought I would report it.

**Comment by cy6erGn0m** [comment]
Modifying tag attributes is impossible after tag content appended and already written. So it's as deaigned

**Comment by wilyarti** [comment]
Ok I wasn't sure if it was a bug.
