### ISSUE TITLE
Error When Creating a Fat Jar

### ISSUE THREAD

**Issue by wellingtoncosta** [ktorio/ktor#916]
### Ktor Version

1.1.2

### Ktor Engine Used(client or server and name)

Netty

### JVM Version, Operating System and Relevant Context

OpenJDK 1.8.0_191, Ubuntu 18.04.1

### Feedback

I'm trying to create a Fat Jar by following the tutorial described in docs, but I'm getting the following the stacktrace:

```
2019-01-31 20:03:25.128 [main] TRACE Application - No configuration provided: neither application.conf nor system properties nor command line options (-config or -P:ktor...=) provided
Exception in thread "main" java.lang.IllegalArgumentException: Neither port nor sslPort specified. Use command line options -port/-sslPort or configure connectors in application.conf
        at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt:121)
        at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt)
        at io.ktor.server.engine.ApplicationEngineEnvironmentBuilder.build(ApplicationEngineEnvironment.kt:95)
        at io.ktor.server.engine.ApplicationEngineEnvironmentKt.applicationEngineEnvironment(ApplicationEngineEnvironment.kt:40)
        at io.ktor.server.engine.CommandLineKt.commandLineEnvironment(CommandLine.kt:50)
        at io.ktor.server.netty.EngineMain.main(EngineMain.kt:16)
        at io.ktor.server.netty.DevelopmentEngine.main(EngineMain.kt:43)
```

**Comment by WellingtonCosta** [comment]
Hi,

Any solution?

**Comment by accursoft** [comment]
The [application plugin](https://docs.gradle.org/current/userguide/application_plugin.html) doesn't create a fat jar, but it's a more reliable packager.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-683">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by devasx666** [comment]
I solved this problem by this method, explicitly start the server since Ktor does not see the foil **application.conf**

```
    embeddedServer(Netty, port = 8080) {
        moduleConf()
        moduleAuth()
        moduleRegistration()
    }.start(wait = true)
```

**Comment by amid67** [comment]
I have the same issue:

`fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)
`

`Exception in thread "main" java.lang.IllegalArgumentException: Neither port nor sslPort specified. Use command line options -port/-sslPort or configure connectors in application.conf
        at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt:129)
        at io.ktor.server.engine.CommandLineKt$commandLineEnvironment$environment$1.invoke(CommandLine.kt)
        at io.ktor.server.engine.ApplicationEngineEnvironmentBuilder.build(ApplicationEngineEnvironment.kt:104)
        at io.ktor.server.engine.ApplicationEngineEnvironmentKt.applicationEngineEnvironment(ApplicationEngineEnvironment.kt:44)
        at io.ktor.server.engine.CommandLineKt.commandLineEnvironment(CommandLine.kt:57)
        at io.ktor.server.netty.EngineMain.main(EngineMain.kt:21)`

**Comment by johnstcn** [comment]
FWIW, I was able to solve this issue for myself by taking the following steps:

1) Commenting out the `sourceSets{...}` stanza in `build.gradle`

2) Ensuring that my project structure looked similar to the following on-disk, which appears to be what the `shadow` plugin wants to see:
```
src/
    main/
        kotlin/
            com/
                company/
                    appname/
                        Application.kt
    resources/
        application.conf
test/
    kotlin/
        com/
            company/
                appname/
                    ApplicationTest
```

**Comment by espen-j** [comment]
This is still an issue, when using Maven and building a fat jar.
