### ISSUE TITLE
ApplicationEngine NoClassDefFoundError

### ISSUE THREAD

**Issue by KubenQPL** [ktorio/ktor#978]
### Ktor Version
1.1.3
### Ktor Engine Used(client or server and name)
ktor-server-netty
### JVM Version, Operating System and Relevant Context
JVM 1.8.0_181, Windows 10
### Feedback
While trying to run my generated jar i am getting NoClassDefFoundError:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: io/ktor/server/engine/ApplicationEngine
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.ktor.server.engine.ApplicationEngine
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```
And this is my gradle part about generating jar:
```groovy
jar {
    baseName 'blog'
    manifest {
        attributes(
                'Class-Path': configurations.compile.collect { it.getName() }.join(' '),
                'Main-Class': 'pl.jakubneukirch.blog_aplikacje.MainKt'

        )
    }

    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}
```

It is worth to mention that when i run app from IDE it works fine

**Comment by cy6erGn0m** [comment]
Was is the jars content? Most likely you have packaged something wrong so you get JNI error. I would say it's something ktor specific. 
You can also follow the following guide to build a fatjar https://ktor.io/servers/deploy/packing/fatjar.html

**Comment by KubenQPL** [comment]
When i tried using fat jar i was getting error saying that manifest attributes can't be null even when i was setting Main-Class: 'package.class' hardcoded.

**Comment by KubenQPL** [comment]
Ok, i cleared my gradle file and written it again, and now fat JAR works fine.

Is fat JAR exporting recommended way of exporting?
